OpenAEV-Platform/openaev

openex-api/pom.xml, openex-api/src/main/java/io/openex/config/AppConfig.java, openex-api/src/main/java/io/openex/config/MvcConfig.java
* https://github.com/OpenEx-Platform/openex/issues/321
=> [api] Fix swagger rendering

openex-api/src/main/java/io/openex/migration/V2_61__Inject_not_null_depends_duration.java, openex-api/src/main/java/io/openex/rest/inject/form/InjectInput.java, openex-api/src/main/java/io/openex/rest/inject/form/InjectUpdateTriggerInput.java, openex-api/src/test/java/io/openex/injects/InjectCrudTest.java, openex-front/src/admin/components/exercises/injects/InjectPopover.js, openex-front/src/admin/components/exercises/injects/QuickInject.js, openex-model/src/main/java/io/openex/database/model/Inject.java
* https://github.com/OpenEx-Platform/openex/issues/345
* https://github.com/OpenEx-Platform/openex/issues/257
=> [backend/frontend] Add constraint on inject's depends duration property

openex-api/src/main/java/io/openex/importer/V1_DataImporter.java, openex-api/src/main/java/io/openex/rest/exercise/ExerciseApi.java, openex-api/src/main/java/io/openex/rest/exercise/exports/VariableMixin.java, openex-api/src/main/java/io/openex/rest/exercise/exports/VariableWithValueMixin.java, openex-front/src/admin/components/exercises/ExercisePopover.tsx
* https://github.com/OpenEx-Platform/openex/issues/411
=> [api] Export variables with values

Dockerfile, openex-front/package.json, openex-front/yarn.lock, renovate.json
add apexcharts to renovate ignore
upgrade Dockerfile builder front image
=> [all] downgrade apexcharts to working version

openex-api/src/main/java/io/openex/injects/challenge/ChallengeContract.java, openex-api/src/main/java/io/openex/injects/media/MediaContract.java
* https://github.com/OpenEx-Platform/openex/issues/462
=> [backend] Changed unavailable variable in injects (#462)

openex-api/src/main/java/io/openex/rest/HomeApi.java
https://github.com/OpenEx-Platform/openex/issues/473
=> [backend] Handle back-end routes

openex-api/pom.xml, openex-api/src/main/java/io/openex/migration/V2_70__Enhance_attack_patterns.java, openex-api/src/main/java/io/openex/rest/attack_pattern/form/AttackPatternCreateInput.java, openex-api/src/main/resources/application.properties, openex-front/src/actions/Schema.js, openex-front/src/admin/components/settings/attack_patterns/AttackPatternPopover.js, openex-front/src/admin/components/settings/attack_patterns/AttackPatterns.js, openex-front/src/components/KillChainPhaseField.js, openex-front/src/utils/Option.ts, openex-model/src/main/java/io/openex/database/model/AttackPattern.java, openex-model/src/main/java/io/openex/database/model/KillChainPhase.java, openex-model/src/main/java/io/openex/database/repository/AttackPatternRepository.java, openex-model/src/main/java/io/openex/database/repository/KillChainPhaseRepository.java
* [backend/frontend] Modelize killchains and attack patterns (#506)
=> [backend/frontend] Modelize killchains and attack patterns (#506)

openex-api/src/main/java/io/openex/rest/user/form/player/UpdatePlayerInput.java, openex-api/src/main/java/io/openex/rest/user/form/user/UpdateUserInput.java, openex-front/src/admin/components/profile/ProfileForm.js, openex-front/src/admin/components/settings/users/UserForm.js, openex-front/src/admin/components/teams/players/PlayerForm.tsx, openex-front/src/utils/Localization.js
=> [frontend] adding check on landline phone in player form (#515)

.github/workflows/test-feature-branch.yml, Dockerfile_ga
* Added feature branch capabilities to Actions
This needs to be merge to master in order to be tested
=> Openex featurebranch actions

openex-api/src/test/java/io/openex/rest/UserApiTest.java, openex-model/src/main/java/io/openex/database/model/User.java
* https://github.com/OpenEx-Platform/openex/issues/576
=> Ensure uniqueness of email field when creating a user account

openbas-front/src/public/components/login/LoginError.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/633
=> [frontend] Fix additional query params lead to error display (#633)

openbas-api/src/main/java/io/openbas/migration/V2_71__Modify_inject.java
* https://github.com/OpenBAS-Platform/openbas/issues/637
=> [backend] Fix migration issue for inject expectation group

openex-api/src/main/java/io/openex/rest/exercise/ExerciseApi.java, openex-api/src/main/java/io/openex/rest/exercise/ExercisePlayerApi.java, openex-front/src/actions/Lessons.js, openex-front/src/public/components/lessons/LessonsPlayer.js
Related issue: https://github.com/OpenBAS-Platform/openbas/issues/654
=> [backend/frontend] - Fix survey page access - 3.5.0

openbas-api/src/main/java/io/openbas/atomic_testing/AtomicTestingService.java, openbas-front/src/admin/components/atomictestings/AtomicTestings.tsx, openbas-front/src/admin/components/atomictestings/atomictesting/AtomicTesting.tsx, openbas-front/src/admin/components/atomictestings/atomictesting/Header.tsx, openbas-front/src/admin/components/components/atomictestings/ResponsePie.tsx, openbas-front/src/admin/components/components/atomictestings/StatusChip.tsx, openbas-front/src/admin/components/components/atomictestings/TargetChip.tsx, openbas-front/src/admin/components/components/atomictestings/TargetResultsDetail.tsx, openbas-front/src/utils/Localization.js, openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java
**Page all atomics: Stephanya**
- ~~Status: Failed, done, progress, pending~~
- ~~Modify Status column name → Inject Execution Status~~
- ~~Pagination search filter custom spec~~
**Page Result atomic (response/detail) : Stephanya**
- ~~Show status aside of title of inject~~
- ~~If we dont have data, show pie chart/ graphs in gray~~
- ~~Add icon asset, asset group, teams on target list, not labels~~
**Launch : Stephanya**
- ~~Delete results execution pop up~~
- ~~Not set default values in target responses (score=0 → score = null)~~
- ~~Change message try: “This execution going to delete all previous status”~~
**Stepper: Stephanya**
- ~~Modify label of step finished→ ended~~
- ~~Stepper bigger~~
- ~~Center Icon~~
* 642- atomic testings
If this is a relatively large or complex change, kick …
=> Page all view and results

openbas-api/src/main/java/io/openbas/rest/attack_pattern/AttackPatternApi.java, openbas-api/src/main/java/io/openbas/rest/attack_pattern/form/AttackPatternUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/kill_chain_phase/form/KillChainPhaseCreateInput.java, openbas-api/src/main/java/io/openbas/rest/kill_chain_phase/form/KillChainPhaseUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/PlatformSettingsApi.java, openbas-front/src/admin/components/settings/attack_patterns/AttackPatternPopover.js, openbas-front/src/admin/components/settings/attack_patterns/AttackPatterns.js, openbas-front/src/admin/components/settings/attack_patterns/CreateAttackPattern.js, openbas-front/src/admin/components/settings/kill_chain_phases/CreateKillChainPhase.js, openbas-front/src/admin/components/settings/kill_chain_phases/KillChainPhaseForm.js, openbas-front/src/admin/components/settings/kill_chain_phases/KillChainPhasePopover.js, openbas-front/src/admin/components/settings/kill_chain_phases/KillChainPhases.js, openbas-front/src/admin/components/settings/tags/CreateTag.js, openbas-front/src/admin/components/settings/tags/TagPopover.js, openbas-front/src/admin/components/settings/tags/Tags.js
* In Settings ⇒ Parameters, form platform name, etc. is not filled / not working
* Optimistic update → Tags
* Attackpattern & Killchainphases not working properly
=> [backend/frontend] Fix settings values and optimistic update in taxonomies section

openbas-api/src/main/java/io/openbas/atomic_testing/AtomicTestingMapper.java, openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseUtils.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseSimple.java, openbas-front/src/admin/components/exercises/ExerciseList.tsx, openbas-front/src/utils/api-types.d.ts
* Add target in simulation list
=> [backend/frontend] Add target in simulation list

openbas-api/src/main/java/io/openbas/config/SessionManager.java
=> [backend] fix cast user to OpenBasPrincipal

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingResult.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/ResponsePie.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx, openbas-front/src/admin/components/simulations/ExerciseList.tsx, openbas-front/src/components/ItemTags.js
* truncate text for tags in scenarios
* Date in 2 rows in french or english
* pending color
* sort expectaion types after creation
*
*
=> [frontend] Style

openbas-api/src/main/java/io/openbas/atomic_testing/AtomicTestingUtils.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetListItem.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx
* All children and sort expectation types, spacing between targets
Global score: 3 responses (2 groups, 1 asset)
*
*
=> [backend/frontend] Show all children in target results

openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java
=> [backend] fix lazy load

openbas-front/src/admin/components/simulations/simulation/dashboard/DashboardResultsStatistics.js, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreByTeam.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreByTeamInPercentage.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreOverTimeByTeam.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreOverTimeByTeamInPercentage.tsx
=> [frontend] ignore expectations without teams for teams graphs

openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreByTeamInPercentage.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreOverTimeByTeamInPercentage.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Team.java
*Score Total is not correct
* With Fix (Just expectation for x exercise )
*
*
=> [backend] Fix scores from teams

openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java, openbas-front/src/admin/components/scenarios/scenario/ScenarioDistributionByExercise.tsx
=> [frontend] fix y axis for simulation results

openbas-model/src/main/java/io/openbas/database/model/Scenario.java
* Adding a safety to avoid NPE when the platform is null (which should not happen in normal cases)
* issue #871 
* issue #869
=> [backend] Remove null objects as a safety measure to avoid NPE

openbas-front/src/admin/components/Dashboard.tsx, openbas-front/src/admin/components/common/simulate/PaperMetric.tsx
* Changes on the global counts and adding the progression counts
*
* issue #845 
*
=> [frontend] Fixing the global counts on the admin page

openbas-api/src/main/java/io/openbas/collectors/fake_detector/FakeDetectorCollector.java, openbas-api/src/main/java/io/openbas/config/MvcConfig.java, openbas-api/src/main/java/io/openbas/config/ThreadPoolTaskSchedulerConfig.java, openbas-api/src/main/java/io/openbas/injectors/caldera/CalderaGarbageCollector.java, openbas-api/src/main/java/io/openbas/rest/injector/InjectorApi.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-api/src/main/resources/application.properties, openbas-framework/src/main/java/io/openbas/asset/QueueService.java, openbas-framework/src/main/java/io/openbas/execution/Executor.java, openbas-framework/src/main/java/io/openbas/executors/caldera/CalderaExecutor.java, openbas-framework/src/main/java/io/openbas/executors/tanium/TaniumExecutor.java
* Properly close RabbitMQ Connections
* Better management of thread by using pooling
* Support for compression
* issue #898 
*
This a first step into better performance and maintanability. A better management of exception would also help a lot but will be taken care of in another PR.
=> [backend] Improving performance

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingHeader.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioHeader.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseHeader.tsx
https://github.com/OpenBAS-Platform/openbas/issues/861
=> [Frontend]Align simulations start button

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java, openbas-front/src/admin/components/scenarios/scenario/ScenarioPopover.tsx
https://github.com/OpenBAS-Platform/openbas/issues/839
=> [backend/frontend] Fix import scenario

openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-front/src/actions/Inject.js, openbas-front/src/admin/components/common/injects/InjectDistributionByType.tsx, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/scenarios/scenario/Index.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/scenarios/scenario/injects/ScenarioInjects.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts, openbas-front/src/admin/components/simulations/simulation/Index.tsx, openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx, openbas-front/src/admin/components/simulations/simulation/lessons/Lessons.js, openbas-front/src/admin/components/simulations/simulation/mails/MailDistributionByInject.tsx, openbas-front/src/admin/components/simulations/simulation/overview/Exercise.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistribution.tsx, openbas-front/src/admin/components/simulations/simulation/reports/Report.js, openbas-front/src/admin/components/simulations/simulation/timeline/InjectOverTimeArea.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/InjectOverTimeLine.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/Timeline.js
https://github.com/OpenBAS-Platform/openbas/issues/897
=> [backend/frontend] Fix trigger now

openbas-front/src/admin/components/assets/endpoints/EndpointsDialogAdding.tsx, openbas-front/src/admin/components/common/injects/InjectDefinition.js, openbas-front/src/admin/components/simulations/simulation/injects/endpoints/InjectAddEndpoints.tsx
*  ![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/822de133-41c0-4402-8504-c2afc007ed7f)
*
*
=> [frontend] add filter to show only targets with the appropriate platform

openbas-api/src/main/java/io/openbas/rest/scenario/form/ScenarioSimple.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-model/src/main/java/io/openbas/database/raw/RawScenario.java, openbas-model/src/main/java/io/openbas/database/repository/ScenarioRepository.java
* Switching get scenarios to raw native query
*
*
*
=> [backend] Switching get scenarios to raw native query

openbas-api/src/main/java/io/openbas/rest/inject/form/InjectExpectationResultsByAttackPattern.java, openbas-api/src/main/java/io/openbas/rest/statistic/StatisticApi.java, openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java, openbas-model/src/main/java/io/openbas/database/raw/RawGlobalInjectExpectation.java, openbas-model/src/main/java/io/openbas/database/raw/RawInjectExpectation.java, openbas-model/src/main/java/io/openbas/database/raw/impl/SimpleRawInjectExpectation.java, openbas-model/src/main/java/io/openbas/database/repository/ExerciseRepository.java
* Switching get statistics to raw native query
*
*
*
=> [backend] Switching get statistics to raw native query

openbas-api/src/main/java/io/openbas/rest/organization/OrganizationApi.java, openbas-model/src/main/java/io/openbas/database/raw/RawOrganization.java, openbas-model/src/main/java/io/openbas/database/repository/OrganizationRepository.java
* Switching get organizations to raw native query
*
*
*
=> [backend] Switching get organizations to raw native query

openbas-api/src/main/java/io/openbas/rest/atomic_testing/form/InjectTargetWithResult.java, openbas-front/src/components/ItemTargets.tsx
* ![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/101ee6d3-e24a-4684-a8ff-e87b2755228a)
*
*
*
=> [backend] remove duplicated targets in simulations

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseSimple.java, openbas-model/src/main/java/io/openbas/database/model/Asset.java, openbas-model/src/main/java/io/openbas/database/model/Inject.java, openbas-model/src/main/java/io/openbas/database/model/InjectExpectation.java, openbas-model/src/main/java/io/openbas/database/raw/RawAsset.java, openbas-model/src/main/java/io/openbas/database/raw/RawAssetGroup.java, openbas-model/src/main/java/io/openbas/database/raw/RawExercise.java, openbas-model/src/main/java/io/openbas/database/raw/RawInject.java, openbas-model/src/main/java/io/openbas/database/raw/RawInjectExpectation.java, openbas-model/src/main/java/io/openbas/database/raw/RawTeam.java, openbas-model/src/main/java/io/openbas/database/raw/impl/SimpleRawInjectExpectation.java, openbas-model/src/main/java/io/openbas/database/repository/AssetGroupRepository.java, openbas-model/src/main/java/io/openbas/database/repository/AssetRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ExerciseRepository.java, openbas-model/src/main/java/io/openbas/database/repository/InjectExpectationRepository.java, openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java, openbas-model/src/main/java/io/openbas/database/repository/TeamRepository.java
* Switching get exercises to raw native query
*
*
*
=> [backend] Switching get exercises to raw native query

openbas-api/src/main/java/io/openbas/helper/RabbitMQHelper.java
* Adding a timeout on the call to rabbitMQ
*
*
*
=> [backend] Adding a timeout on the call to rabbitMQ

openbas-front/src/admin/components/common/articles/Articles.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseDefinition.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1018
=> [frontend] Fix error on definition screen

openbas-api/src/main/java/io/openbas/migration/V3_12__Add_array_union_agg_method.java, openbas-api/src/main/java/io/openbas/migration/V3_16__Add_array_union_agg_method.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/main/java/io/openbas/utils/pagination/PaginationUtils.java, openbas-api/src/main/java/io/openbas/utils/pagination/SortUtilsCriteriaBuilder.java, openbas-framework/src/main/java/io/openbas/utils/JpaUtils.java, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-model/src/main/java/io/openbas/database/raw/RawPaginationScenario.java
* Use Criteria builder to craft pagination query
* Use Specification for Text Search and FIltering
=> [backend/frontend] Improv scenario pagination

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/helper/TeamHelper.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java, openbas-api/src/main/java/io/openbas/rest/team/TeamApi.java, openbas-front/src/admin/components/common/injects/CreateInject.tsx, openbas-front/src/admin/components/common/injects/CreateInjectDetails.js, openbas-front/src/admin/components/components/teams/AddTeams.tsx, openbas-front/src/admin/components/components/teams/TeamAddPlayers.tsx, openbas-front/src/admin/components/components/teams/Teams.tsx, openbas-front/src/admin/components/scenarios/scenario/Index.tsx, openbas-front/src/admin/components/simulations/simulation/Index.tsx, openbas-front/src/admin/components/simulations/simulation/teams/ExerciseTeams.tsx, openbas-model/src/main/java/io/openbas/database/model/SimplerTeam.java, openbas-model/src/main/java/io/openbas/database/model/TeamSimple.java, openbas-model/src/main/java/io/openbas/database/raw/RawCommunication.java, openbas-model/src/main/java/io/openbas/database/raw/RawExerciseTeamUser.java, openbas-model/src/main/java/io/openbas/database/raw/RawInjectExpectation.java, openbas-model/src/main/java/io/openbas/database/raw/RawScenario.java, openbas-model/src/main/java/io/openbas/database/raw/RawTeam.java, openbas-model/src/main/java/io/openbas/database/raw/impl/SimpleRawInjectExpectation.java, openbas-model/src/main/java/io/openbas/database/repository/CommunicationRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ExerciseTeamUserRepository.java, openbas-model/src/main/java/io/openbas/database/repository/InjectExpectationRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ScenarioRepository.java, openbas-model/src/main/java/io/openbas/database/repository/TeamRepository.java
* [backend] Fix on get teams to have them with native queries for better performance AND we get rid of the content of communications as we don't need them
*
*
*
=> [backend] Fix on get teams to have better performance

openbas-api/src/main/java/io/openbas/migration/V3_12__Add_index_for_atomic_testings.java, openbas-api/src/main/java/io/openbas/migration/V3_19__Add_index_for_atomic_testings.java
* Add indexes for atomic testing and joins
*
*
*
=> [backend] add index

openbas-front/src/admin/components/common/articles/Articles.tsx, openbas-front/src/admin/components/components/channels/ChannelsFilter.tsx
=> [frontend] fix channels filter in definition

openbas-api/src/main/java/io/openbas/config/GlobalExceptionHandler.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/form/DirectInjectInput.java, openbas-front/src/admin/components/simulations/simulation/mails/Communication.js, openbas-front/src/admin/components/simulations/simulation/mails/Inject.js
* https://github.com/OpenBAS-Platform/openbas/issues/979
=> [backend/frontend] Fix reply to function in animation>mail section

openbas-front/src/utils/SortingFiltering.js
=> [frontend]Updating the filters document

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseDetails.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseSimple.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseUpdateStatusInput.java, openbas-api/src/main/java/io/openbas/rest/helper/TeamHelper.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-api/src/test/java/io/openbas/helper/InjectHelperTest.java, openbas-api/src/test/java/io/openbas/service/ExerciseExpectationServiceTest.java, openbas-model/src/main/java/io/openbas/database/model/Exercise.java, openbas-model/src/main/java/io/openbas/database/model/ExerciseStatus.java, openbas-model/src/main/java/io/openbas/database/model/ExerciseTeamUser.java, openbas-model/src/main/java/io/openbas/database/model/Inject.java, openbas-model/src/main/java/io/openbas/database/raw/RawEvaluation.java, openbas-model/src/main/java/io/openbas/database/raw/RawExercise.java, openbas-model/src/main/java/io/openbas/database/raw/RawGrant.java, openbas-model/src/main/java/io/openbas/database/raw/RawInject.java, openbas-model/src/main/java/io/openbas/database/raw/RawObjective.java, openbas-model/src/main/java/io/openbas/database/raw/RawPause.java, openbas-model/src/main/java/io/openbas/database/repository/EvaluationRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ExerciseRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ExerciseTeamUserRepository.java, openbas-model/src/main/java/io/openbas/database/repository/GrantRepository.java, openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ObjectiveRepository.java, openbas-model/src/main/java/io/openbas/database/repository/PauseRepository.java, openbas-model/src/main/java/io/openbas/database/specification/ExerciseSpecification.java, openbas-model/src/main/java/io/openbas/database/specification/InjectSpecification.java
* Fix on get exercise details to have better performance
*
*
*
=> [backend] Fix on get exercise details to have better performance

openbas-api/src/main/java/io/openbas/rest/atomic_testing/AtomicTestingApi.java, openbas-api/src/main/java/io/openbas/rest/inject/ExerciseInjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/ScenarioInjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/output/InjectOutput.java, openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-framework/src/main/java/io/openbas/utils/JpaUtils.java, openbas-front/src/actions/Inject.js, openbas-front/src/actions/atomic_testings/atomic-testing-actions.ts, openbas-front/src/actions/injects/inject-action.ts, openbas-front/src/actions/injects/inject-helper.d.ts, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingPopover.tsx, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/injects/InjectDefinition.js, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/common/injects/Injects.js, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/scenarios/scenario/injects/ScenarioInjects.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts, openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx, openbas-front/src/admin/components/simulations/simulation/mails/Mails.js, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx, openbas-front/src/public/components/login/Login.js, openbas-front/src/utils/ArrayUtils.ts, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Inject.java, openbas-model/src/main/java/io/openbas/database/raw/RawInject.java, openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java, openbas-model/src/main/java/io/openbas/helper/InjectModelHelper.java
https://github.com/OpenBAS-Platform/openbas/issues/898
=> [backend/frontend] Improv injects perf

openbas-front/src/admin/components/common/injects/UpdateInject.tsx
=> [frontend] fix

openbas-front/src/admin/components/common/matrix/AttackPatternBox.tsx, openbas-model/src/main/java/io/openbas/database/repository/ExerciseRepository.java
* Fix duplicate inject results on Mitre Matrix
* https://github.com/OpenBAS-Platform/openbas/issues/944
=> [backend/frontend] Fix duplicate inject results

openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java, openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java, openbas-api/src/main/resources/application.properties, openbas-framework/src/main/java/io/openbas/config/OpenBASConfig.java, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/utils.ts
* Adding feature flag
*
*
*
This is based on OpenCTI implementation : https://github.com/OpenCTI-Platform/opencti/blob/8160869e99f4eb0ed56801ab9d9565027e553f4d/opencti-platform/opencti-graphql/src/config/conf.js#L479
=> [backend/frontend] Adding feature flag

.github/workflows/test-feature-branch.yml
=> Update test-feature-branch workflow to use new AWX endpoint

openbas-model/src/main/java/io/openbas/database/converter/ContentConverter.java
=> [backend] filter data null

openbas-api/src/main/java/io/openbas/rest/asset/endpoint/EndpointApi.java, openbas-framework/src/main/java/io/openbas/helper/StreamHelper.java
* Add last seen property when when asset is registered through agent
=> [backend] Add last seen when asset is registered through agent

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseSimple.java, openbas-front/src/admin/components/atomic_testings/InjectList.tsx, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/simulations/ExerciseList.tsx, openbas-front/src/admin/components/simulations/Exercises.tsx, openbas-front/src/utils/api-types.d.ts
* https://github.com/OpenBAS-Platform/openbas/issues/1065
=> [backend/frontend] Sort simulation by updated date

openbas-front/src/admin/components/common/injects/CreateInject.tsx, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/components/common/Drawer.tsx
* Fix on layout of the image not working
*
* issue #883 
*
=> [frontend] Fix on layout of the image no working

openbas-api/src/main/java/io/openbas/scheduler/jobs/ScenarioExecutionJob.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/test/java/io/openbas/scheduler/jobs/ScenarioExecutionJobTest.java, openbas-model/src/main/java/io/openbas/database/specification/ScenarioSpecification.java
* https://github.com/OpenBAS-Platform/openbas/issues/1040
=> [backend] Fix recurring scenario not cleaned

openbas-front/src/admin/components/assets/endpoints/EndpointPopover.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1110
=> When editing an endpoint without description, form cannot be validated

openbas-framework/src/main/java/io/openbas/asset/AssetGroupService.java
* Dynamic filter are just applied on assets type 'endpoint'
* https://github.com/OpenBAS-Platform/openbas/issues/1170
*
=> [backend] Apply dynamic asset groups filter just on assets type endpoint (#1170)

openbas-dev/docker-compose.yml
Adding a DB that can be used as a test DB locally
=> [dev] Add testing DB

openbas-front/src/admin/components/Dashboard.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroupDialogAdding.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroups.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroupsList.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointsDialogAdding.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointsList.tsx, openbas-front/src/admin/components/common/injects/InjectAddDocuments.tsx, openbas-front/src/admin/components/common/injects/InjectAddTeams.tsx, openbas-front/src/admin/components/common/injects/InjectDefinition.js, openbas-front/src/admin/components/common/injects/Injects.js, openbas-front/src/admin/components/common/injects/teams/InjectTeamsList.tsx, openbas-front/src/admin/components/components/teams/AddTeams.tsx, openbas-front/src/admin/components/components/teams/ContextualTeams.tsx, openbas-front/src/admin/components/components/teams/TeamAddPlayers.tsx, openbas-front/src/admin/components/components/teams/TeamPlayers.tsx, openbas-front/src/admin/components/components/teams/Teams.tsx, openbas-front/src/admin/components/payloads/Payloads.js, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/simulations/ExerciseList.tsx, openbas-front/src/admin/components/simulations/simulation/injects/QuickInject.js, openbas-front/src/components/ItemTags.js, openbas-front/src/components/ItemTargets.tsx, openbas-front/src/utils/String.js
* Space for tags, add tooltips, and name with remaining tags :
* Add tooltips, chip with number of remaining tags
* bug/1112
*
=> [frontend] Fix spacing for tags (#1112)

openbas-front/src/admin/components/agents/Agents.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointsDialogAdding.tsx, openbas-front/src/components/PlatformIcon.tsx
=> [Frontend]Fix alignment of platform icons in add assets to inject

openbas-front/src/admin/components/assets/endpoints/Endpoints.tsx
Adding fetchTags to load tags into the store
*
*
*
*
=> [frontend] 1111 - Full reload of the endpoints list, no tags displayed

openbas-front/src/admin/components/common/articles/CreateArticle.js, openbas-front/src/admin/components/common/form/TextFieldAskAI.tsx, openbas-front/src/utils/Localization.js
* Remove limit for showing ask AI button
* Add limit to generate media
* https://github.com/OpenBAS-Platform/openbas/issues/1128
*
=> [frontend] Enable AI button on media pressure article (#1128)

openbas-front/src/admin/components/simulations/ExerciseList.tsx, openbas-front/src/admin/components/simulations/Exercises.tsx, openbas-front/src/components/common/pagination/PaginationComponent.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1167
=> [frontend] Change pagination row per page options

openbas-front/src/admin/components/common/injects/expectations/ExpectationPopover.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1200
=> [frontend] Fix form update expectation

openbas-front/src/public/components/challenges/ChallengesPlayer.js
* https://github.com/OpenBAS-Platform/openbas/issues/1226
=> [frontend] Fix result on challenge flag

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java, openbas-front/package.json, openbas-front/src/admin/components/common/injects/Injects.js, openbas-front/src/admin/components/simulations/ExerciseList.tsx, openbas-front/src/admin/components/simulations/Exercises.tsx, openbas-front/src/admin/components/simulations/ImportUploaderExercise.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseHeader.tsx, openbas-front/src/admin/components/simulations/simulation/ExercisePopover.tsx, openbas-front/src/utils/Localization.js, openbas-front/src/utils/hooks/useExportToXLS.ts, openbas-front/yarn.lock
* https://github.com/OpenBAS-Platform/openbas/issues/1208
=> Wrong format when exporting injects in XLS

openbas-front/src/admin/components/common/injects/CreateInject.tsx
=> [Frontend]Correcting inject icons alignment in inject creation

openbas-api/src/main/java/io/openbas/service/InjectService.java
* Fixing an error when column is empty on expectations
*
*
*
=> [backend] Fixing an error when column is empty on expectations

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java, openbas-api/src/main/java/io/openbas/rest/inject/ExerciseInjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/ScenarioInjectApi.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java, openbas-api/src/main/java/io/openbas/service/ExerciseExpectationService.java, openbas-api/src/main/java/io/openbas/service/GrantService.java, openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/test/java/io/openbas/rest/InjectApiTest.java, openbas-api/src/test/java/io/openbas/utils/mockUser/WithMockObserverUserSecurityContextFactory.java, openbas-api/src/test/java/io/openbas/utils/mockUser/WithMockPlannerUserSecurityContextFactory.java, openbas-front/src/actions/Inject.js, openbas-front/src/admin/components/common/ToolBar.js, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/common/injects/Injects.js, openbas-front/src/admin/components/components/challenges/Challenges.js, openbas-front/src/admin/components/components/channels/Channels.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/scenarios/scenario/injects/ScenarioInjects.tsx, openbas-front/src/admin/components/settings/users/Users.js, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts, openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx, openbas-front/src/components/fields/FileLoader.tsx, openbas-front/src/components/i18n.js, openbas-front/src/utils/Action.js, openbas-front/src/utils/Localization.js, openbas-model/src/main/java/io/openbas/database/repository/CommunicationRepository.java, openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java
* Delete a list of injects in scenarios/exercise.
* Some fix de style
* https://github.com/OpenBAS-Platform/openbas/issues/1157
*
=> [frontend] add delete option for scenarios/exercises

openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/injects/ImportUploaderInjectFromInjectsTest.tsx, openbas-front/src/admin/components/common/injects/ImportUploaderInjectFromXls.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/settings/DataIngestionMenu.tsx, openbas-front/src/admin/components/settings/data_ingestion/XlsFormatters.tsx, openbas-front/src/admin/components/settings/data_ingestion/xls_formatter/XlsMapperTestDialog.tsx, openbas-front/src/components/Message.js, openbas-front/src/components/common/CodeBlock.tsx, openbas-front/src/components/common/IconPopover.tsx, openbas-front/src/utils/Environment.js, openbas-front/src/utils/Localization.js, openbas-model/src/main/java/io/openbas/database/audit/ModelBaseListener.java
* Fix on import of relative time
* Better readibility on log message/injects when testing a mapper
* Comprehensive error message in case of critical error during import
*
*
=> [backend/frontend] Last fixes on import

openbas-front/src/admin/components/common/injects/CreateInject.tsx, openbas-front/src/admin/components/common/injects/InjectIcon.js, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/components/Timeline.tsx, openbas-front/src/components/common/pagination/PaginationComponent.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1203
=> [frontend] Fix timelines is not clickable anymore

openbas-front/src/admin/components/injects/InjectHeader.tsx, openbas-front/src/admin/components/simulations/simulation/injects/InjectIndex.tsx, openbas-front/src/components/Breadcrumbs.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1209
=> [frontend] Change header on inject details

openbas-api/src/main/java/io/openbas/service/InjectService.java
* Fix on import XLS to avoid having the date being set as relative when it's not
*
* #1261 
*
=> [backend] Fix on date being incorrectly set as relative

openbas-api/src/main/java/io/openbas/utils/pagination/SearchPaginationInput.java, openbas-front/src/admin/components/atomic_testings/InjectList.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingHeader.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingPopover.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingUpdate.tsx, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/scenarios/scenario/Scenario.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioHeader.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioPopover.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioUpdate.tsx, openbas-front/src/admin/components/simulations/ExerciseList.tsx, openbas-front/src/admin/components/simulations/Exercises.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseHeader.tsx, openbas-front/src/admin/components/simulations/simulation/ExercisePopover.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1205
=> Delete an item from a list (inject, atomic testing, scenario, simlation)

openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/raw/RawPaginationPlayer.java
* Fix on players not properly displayed
*
* #1304 
*
=> [backend/frontend] Fix on player not properly displayed

openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/UpdateInjectDetails.js
=> Drawer effect is not correct when opening an inject from the list

openbas-front/src/admin/components/common/simulate/EmailParametersForm.tsx
* Fix on email adresses to trim them
* Have a better error message when the email is not valid
* #1220 
* #1219 
=> [frontend] Fix on email adresses

openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioImportApi.java, openbas-api/src/main/java/io/openbas/rest/scenario/form/InjectsImportInput.java, openbas-front/src/actions/scenarios/scenario-actions.ts, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/injects/ImportUploaderInjectFromXls.tsx, openbas-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/utils/api-types.d.ts
* Allow user to configure a launch time during import if needed
*
* #1246 
*
=> [backend/frontend] Allow user to configure a launch time during import if needed

openbas-framework/src/main/java/io/openbas/execution/ExecutionContextService.java, openbas-front/src/admin/components/simulations/simulation/lessons/Lessons.js, openbas-front/src/public/components/lessons/LessonsPlayer.js
* Add Exercise variable on executionContext
* Avoid set 0 as score on lessons
* Style
* https://github.com/OpenBAS-Platform/openbas/issues/1234
*
=> [backend/frontend] Fix score in learned lessons

openbas-front/src/admin/components/atomic_testings/InjectList.tsx, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/simulations/ExerciseList.tsx
* Aligned list columns headers
*  https://github.com/OpenBAS-Platform/openbas/issues/1259
=> [frontend] aligned list columns headers #1259

openbas-front/src/admin/components/atomic_testings/InjectList.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1184
I start digging on this issue.
Still some work to do
=> [frontend] Remove double fetch

.github/workflows/test-feature-branch.yml
=> Fixed obas url for dev deploy and template id in AWX

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseImportApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioImportApi.java, openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-api/src/test/java/io/openbas/service/InjectServiceTest.java, openbas-front/src/actions/exercises/exercise-action.ts, openbas-front/src/actions/scenarios/scenario-actions.ts, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts, openbas-model/src/main/java/io/openbas/database/model/Exercise.java
* https://github.com/OpenBAS-Platform/openbas/issues/1247
=> [backend/frontend] Ability to import XLS and use XLS mapper into Simulation

openbas-front/src/admin/components/settings/groups/GroupPopover.js
* Bug fix to refresh groups
* Display problem not updated on Groups (#1348)
=> [frontend] Display problem not updated on Groups (#1348)

openbas-front/src/actions/exercises/exercise-action.ts
=> [frontend] Fix url for exercise

openbas-api/src/main/java/io/openbas/rest/atomic_testing/form/InjectResultDTO.java, openbas-api/src/main/java/io/openbas/service/InjectTestStatusService.java, openbas-front/src/actions/injects/inject-action.ts, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/common/ToolBar.js, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/utils/Localization.js, openbas-model/src/main/java/io/openbas/database/model/Inject.java, openbas-model/src/main/java/io/openbas/database/specification/InjectSpecification.java
- Reduce time execution for bulk test inject
- Remove check on teams -> when we test an inject, emails or SMS are send to the current user. Teams are not used.
- Remove InjectTestStatus on Inject class -> is not used
=> [backend/frontend] Fix inject test condition

.github/workflows/auto-set-label.yml
* Adding a way to have the labels automatically set so I can stop forgetting them
*
*
*
=> [github] Adding a way to have the labels automatically set

.github/workflows/auto-set-label.yml
* Small fix on the new workflow
*
*
*
=> [github] Fixing the branch name

openbas-front/src/admin/components/scenarios/Scenarios.tsx
=> [Frontend] Fix spaces between overlay and separators in scenario tab

openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/scenarios/scenario/injects/ScenarioInjects.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts, openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx
When we are on the inject list on the inject (scenario or simulation) and we do an action in the popover, the list is not updated.
=> [frontend] Fix inject action update in inject list

openbas-front/src/actions/exercises/exercise-action.ts
When I send a survey, I receive it BUT I have this message
=> [frontend] Error display when a survey is send

openbas-front/src/admin/components/common/injects/InjectChainsForm.js, openbas-front/src/utils/Localization.js
* Adding a small padding on the condition
* Better message in the condition form
*
*
=> [frontend] Small fix on chaining UI

openbas-framework/src/main/java/io/openbas/utils/OperationUtilsJpa.java, openbas-front/src/components/common/queryable/filter/FilterChip.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1457
=> [backend/frontend] Improv filters UI

openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
issue : https://github.com/OpenBAS-Platform/openbas/issues/1412
=> [frontend] can done and trigger inject only in animation tab

openbas-api/src/main/java/io/openbas/service/AtomicTestingService.java
* Fix the case in which expectations were not added
* https://github.com/OpenBAS-Platform/openbas/issues/1425
=> [backend] Fix expectations in injects (#1425)

openbas-front/src/components/AppIntlProvider.js, openbas-front/src/utils/Action.ts, openbas-front/src/utils/Localization.js
=> [frontend] fix translation in network success or fail messages (#1482)

openbas-front/src/admin/components/assets/endpoints/Endpoints.tsx, openbas-model/src/main/java/io/openbas/database/model/Asset.java
Closes #1456 
- make asset_executor attribute sortable
- replace endpoint_executor with asset_executor
- https://github.com/OpenBAS-Platform/openbas/issues/1456
=> [backend/frontend] Sorting on "executor" in "Endpoints" section triggers "Internal error"

.github/PULL_REQUEST_TEMPLATE.md
* Add "Closes #ISSUE-NUMBER" in PR TEMPLATE
=> [github] update PULL_REQUEST_TEMPLATE.md

openbas-front/src/admin/components/simulations/simulation/timeline/InjectOverTimeArea.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/InjectOverTimeLine.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
* Update graphs with filtered injects
* ![image](https://github.com/user-attachments/assets/cb2a4f4c-35d1-4598-b63b-fcb5ddd06d62)
* ![image](https://github.com/user-attachments/assets/03d0a02a-6327-4579-9c95-c8433c405811)
* Closes https://github.com/OpenBAS-Platform/openbas/issues/1503
*
=> [frontend] Fix filter tags on timeline overview

openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-api/src/test/java/io/openbas/service/InjectServiceTest.java
* Only add the tuple scenario/team/user if does not already exists
*
* #1476 
*
=> [backend] Small fix on adding a tuple scenario/teams/users

openbas-api/pom.xml, openbas-api/src/main/resources/application.properties, openbas-api/src/main/resources/logback-spring.xml
* Setting the logs to json format when not in dev
*
* Closes #1418 
*
=> [backend] Improvment - better logging

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingDetail.tsx
* Show commands lines section in atomic testing details if they exist
=> [frontend] Show commands lines section only if exist

openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java, openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java, openbas-api/src/main/resources/application.properties, openbas-framework/src/main/java/io/openbas/expectation/ExpectationPropertiesConfig.java, openbas-front/src/admin/components/common/injects/expectations/ExpectationFormCreate.tsx, openbas-front/src/admin/components/common/injects/expectations/ExpectationPopover.tsx, openbas-front/src/utils/api-types.d.ts
* Adding a default value on manual expectations
*
* 
*
=> [frontend/backend] Setting a default value to the manual expectations

openbas-api/src/main/java/io/openbas/expectation/ExpectationType.java, openbas-api/src/main/java/io/openbas/utils/AtomicTestingMapper.java, openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java
* https://github.com/OpenBAS-Platform/openbas/issues/1608
Should be merged before this PR
https://github.com/OpenCTI-Platform/opencti/pull/8589
=> [backend] Add ID on expectation type

openbas-api/src/main/java/io/openbas/helper/RabbitMQHelper.java, openbas-api/src/main/resources/application.properties, openbas-api/src/test/resources/application.properties, openbas-framework/src/main/java/io/openbas/config/RabbitmqConfig.java
* Fix on use of ssl when calling the management plugin of rabbitmq
*
* Closes #1618 
*
=> [backend] Fix call to the management plugin not working when using ssl

openbas-front/src/admin/components/common/injects/UpdateInject.tsx
- Wait for Inject to load before being able to edit
- Closes #1629
=> [frontend] Documents are not duplicated when an inject is duplicated

openbas-front/src/components/fields/SelectField.jsx
=> [frontend] fix passing props to select field (#1632)

openbas-front/src/components/ChainedTimeline.tsx, openbas-front/src/static/css/index.css
* Fix mouse cursor disappearing
*
* Closes #1658 
*
=> [frontend] Fix mouse cursor disappearing (#1658)

openbas-api/src/main/java/io/openbas/rest/payload/form/PayloadUpsertInput.java
* Fix type of status and source on upsert dto
*
*
=> [backend] Update dto upsert payload

openbas-framework/src/main/java/io/openbas/injector_contract/variables/VariableHelper.java
* Modify description of user variables
*
* Closes [#38](https://github.com/OpenBAS-Platform/docs/issues/38)
*
=> [backend] Update description of user variables

openbas-front/builder/dev/dev.js, openbas-front/package.json, openbas-front/yarn.lock
=> [frontend] Fix deprecated start method to start frontend (#1678)

openbas-front/src/admin/components/simulations/simulation/reports/InjectReportResult.tsx
=> [frontend] fix import icon

openbas-front/src/admin/components/settings/groups/Groups.js
=> [frontend] delete double fetch in groups (#1699)

openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASImplantExecutor.java
=> [backend] Add obfuscator base64 on expectation signature for OpenBAS agent

openbas-framework/src/main/java/io/openbas/utils/OperationUtilsRuntime.java
* Small fix on filters when filtering on an enum
*
* 
*
=> [backend] Small fix on filters when filtering on an enum

openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-front/src/admin/components/common/injects/InjectChainsForm.tsx, openbas-front/src/components/ChainedTimeline.tsx, openbas-front/src/components/common/chaining/ChainingUtils.tsx, openbas-front/src/components/nodes/NodeInject.tsx
* Better node positionning
* Labels on edges
* Closes #1385 
*
=> [frontend] Chaining injects logically - UI Improvements

openbas-api/src/main/java/io/openbas/rest/atomic_testing/AtomicTestingApi.java, openbas-api/src/main/java/io/openbas/rest/team/AtomicTestingTeamApi.java, openbas-api/src/main/java/io/openbas/rest/team/ExerciseTeamApi.java, openbas-api/src/main/java/io/openbas/rest/team/ScenarioTeamApi.java, openbas-api/src/main/java/io/openbas/rest/team/TeamApi.java, openbas-api/src/main/java/io/openbas/rest/team/TeamQueryHelper.java, openbas-api/src/main/java/io/openbas/rest/team/output/TeamOutput.java, openbas-front/src/actions/atomic_testings/atomic-testing-actions.ts, openbas-front/src/actions/exercises/exercise-teams-action.ts, openbas-front/src/actions/scenarios/scenario-teams-action.ts, openbas-front/src/admin/components/atomic_testings/AtomicTestings.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingUpdate.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/Index.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/context/TeamContextForAtomicTesting.tsx, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/injects/CreateInjectDetails.js, openbas-front/src/admin/components/common/injects/InjectAddTeams.tsx, openbas-front/src/admin/components/common/injects/InjectDefinition.js, openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/UpdateInjectDetails.js, openbas-front/src/admin/components/common/injects/teams/InjectTeamsList.tsx, openbas-front/src/admin/components/components/teams/TeamAddPlayers.tsx, openbas-front/src/admin/components/components/teams/TeamPopover.tsx, openbas-front/src/admin/components/scenarios/scenario/teams/ScenarioTeams.tsx, openbas-front/src/admin/components/simulations/simulation/injects/QuickInject.js, openbas-front/src/admin/components/simulations/simulation/teams/ExerciseTeams.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx, openbas-front/src/admin/components/teams/players/PlayerPopover.tsx, openbas-front/src/utils/api-types.d.ts
* Change teams call to use new teams endpoint to improv performance
* Change component when select teams on create and update inject (in scenario/simulation/atomic testing)
=> [backend/frontend] Improv team performance

openbas-front/src/admin/components/common/injects/InjectChainsForm.tsx
* Small fix on adding a new parent using the tab
*
* 
*
=> [frontend] Small fix on adding a new parent using the tab

openbas-api/src/main/java/io/openbas/service/AtomicTestingService.java
* Fix on assets not well displayed
*
* 
*
=> [backend] Assets are not well displayed

openbas-front/src/admin/components/integrations/injectors/injector_contracts/InjectorContractCustomForm.js, openbas-front/src/admin/components/integrations/injectors/injector_contracts/InjectorContractForm.js
align UI buttons for inject contract
=> [frontend] align UI buttons for injector contract

openbas-api/src/main/java/io/openbas/service/AtomicTestingService.java
* Remove unnecessary set of depends on
* Closes NO-ISSUE
=> [backend] Update an atomic testing is not working

openbas-front/src/components/ChainedTimeline.tsx
* Setting the edges to a bezier curve
*
* 
*
=> [frontend] Setting edges to a bezier curve in timeline

openbas-api/src/main/java/io/openbas/rest/group/GroupApi.java
* Remove publish of scenario and simulation update
* Closes #1347
=> [backend] Error 500 when updating Groups

openbas-framework/src/main/java/io/openbas/inject_expectation/InjectExpectationService.java
=> [backend] fix computeExpectation when score is 0 (#1663)

openbas-front/src/root.tsx
=> [frontend] when refresh do not display login page

openbas-front/src/admin/components/Dashboard.tsx
=> [frontend] fix label for top attack pattern chart in dashboard (#1815)

openbas-api/src/main/resources/application.properties, openbas-model/src/main/java/io/openbas/config/MinioConfig.java, openbas-model/src/main/java/io/openbas/config/S3Config.java, openbas-model/src/main/java/io/openbas/driver/MinioDriver.java
* Added a boolean in the config to use aws iam role
* Added the possibility to use a custom sts endpoint
* Closes #1453 
*
=> [backend] Allow for use of AWS IAM Role

openbas-api/src/main/java/io/openbas/rest/payload/PayloadApi.java, openbas-api/src/main/java/io/openbas/rest/payload/form/PayloadUpsertInput.java
* Fix on upsert payload not setting the platform
*
* 
*
=> [backend] Fix on upsert payload not updating the platform

openbas-front/src/admin/components/atomic_testings/AtomicTestings.tsx, openbas-front/src/admin/components/atomic_testings/InjectResultList.tsx
=> [frontend] Fix popover atomic testing

openbas-api/src/main/java/io/openbas/injectors/caldera/service/CalderaInjectorService.java, openbas-api/src/main/java/io/openbas/injectors/caldera/service/CalderaResultCollectorService.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/ComchecksExecutionJob.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-api/src/test/java/io/openbas/runner/InitAdminCommandLineRunnerTest.java, openbas-model/src/main/java/io/openbas/database/model/DryInjectStatus.java, openbas-model/src/main/java/io/openbas/database/model/Execution.java
* Fix cases of comparison between InjectStatus vs IjectTracestatus
*
=> [backend] Fix status traces comparisons

openbas-front/src/admin/components/common/injects/Injects.tsx
=> [frontend] correct inject list popover

openbas-front/src/admin/components/lessons/exercises/LessonsCategories.js
*Adding margin to the Lesson Learned list so the first category is display properly
Before
After
* Closes [1624](https://github.com/OpenBAS-Platform/openbas/issues/1624)
=> [frontend] fixed Lessons Learned screen

openbas-api/src/main/java/io/openbas/injectors/ovh/OvhSmsExecutor.java, openbas-front/src/admin/components/components/teams/ContextualTeams.tsx, openbas-front/src/admin/components/simulations/simulation/mails/Mails.js, openbas-front/src/admin/components/simulations/simulation/overview/Exercise.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistribution.tsx
Fix: 
- Throw error on SMS executor when number is invalid
- Display teams on quick inject
- Add padding on simulation overview
=> [frontend] Display teams on quick inject

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java, openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java
* Fix on importing simulations
*
* Closes #1928 
*
=> [backend] Fix on importing simulations (#1928)

openbas-api/src/main/resources/application.properties
* Removing placeholder in sts endpoint property
*
* 
*
=> [backend] Removing placeholder on sts endpoint

openbas-front/src/components/fields/TagField.tsx
* Fixed the format of the "newTags" array in the TagField component, so the new tag is displayed properly
* Closes #1706
=> [frontend] Fixed Tag creation method #1706

openbas-api/src/main/java/io/openbas/migration/V3_50__Adding_wrapper_functions.java
* Fixing migration number
*
* 
*
=> [backend] Fixing migration number

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingResult.tsx
Add tooltip on simulations global score
=> [frontend] Add tooltip on global score (#1763)

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java, openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/exports/ExerciseExportMixins.java, openbas-api/src/main/java/io/openbas/rest/payload/PayloadApi.java, openbas-api/src/main/java/io/openbas/rest/payload/PayloadCreationService.java, openbas-api/src/main/java/io/openbas/rest/payload/PayloadUtils.java, openbas-api/src/test/java/io/openbas/rest/PayloadApiTest.java, openbas-model/src/main/java/io/openbas/database/model/InjectorContract.java, openbas-model/src/main/java/io/openbas/database/specification/InjectorContractSpecification.java
* https://github.com/OpenBAS-Platform/openbas/issues/1992
=> [backend] Fix import/export with unknown contract ID

openbas-model/pom.xml, pom.xml
* Overriding spring's postgresql dependency to prevent a critical CVE
*
* Closes #1771 
*
=> [backend] Overriding spring's postgresql dependency

openbas-api/src/main/java/io/openbas/rest/inject/form/InjectExpectationResultsByAttackPattern.java, openbas-front/src/admin/components/common/matrix/AttackPatternBox.tsx, openbas-front/src/admin/components/common/matrix/KillChainPhaseColumn.tsx, openbas-front/src/utils/api-types.d.ts
* Propagate a link to specific simulation injects when navigating into MITRE matrix menu elements
* Closes #1966
*
=> [frontend/backend] Make inject result element clickable in MITRE matrix on Simulation overview (#1966)

.circleci/config.yml
* fix a typo for the no_output_timeout
*
*
=> [tool] fix drone & circle for prerelease platform (#1909)

openbas-front/src/actions/asset_groups/assetgroup-helper.d.ts, openbas-front/src/actions/assets/asset-helper.d.ts, openbas-front/src/actions/channels/Article.d.ts, openbas-front/src/actions/channels/article-helper.d.ts, openbas-front/src/admin/components/Dashboard.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroupAddEndpoints.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroupCreation.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroupManagement.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroupPopover.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroups.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointCreation.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointPopover.tsx, openbas-front/src/admin/components/assets/endpoints/Endpoints.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointsDialogAdding.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointsList.tsx, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/articles/Articles.tsx, openbas-front/src/admin/components/common/injects/InjectAddArticles.tsx, openbas-front/src/admin/components/common/injects/InjectAddTeams.tsx, openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/components/teams/UpdateTeams.tsx, openbas-front/src/admin/components/scenarios/scenario/Scenario.tsx, openbas-front/src/admin/components/scenarios/scenario/articles/articleContextForScenario.ts, openbas-front/src/admin/components/simulations/Exercises.tsx, openbas-front/src/admin/components/simulations/simulation/articles/articleContextForExercise.ts, openbas-front/src/admin/components/simulations/simulation/validation/common/TeamOrAssetLine.tsx, openbas-front/src/admin/components/simulations/simulation/validation/expectations/TechnicalExpectationAssetGroup.tsx
Follow up this PR
https://github.com/OpenBAS-Platform/openbas/pull/1999
=> [frontend] Remove EndpointStore, AssetGroupStore & ArticleStore

.circleci/config.yml
=> [tool] fix circle prerelease regex (#1909)

.circleci/config.yml
=> [tool] fix latest tag incorrectly points to a lower semver (#2051)

.circleci/config.yml, openbas-api/src/main/resources/application.properties
=> [tool/backend] fix agent & implant fetching (#1909)

openbas-front/src/admin/components/simulations/simulation/lessons/ExerciseLessons.tsx, openbas-front/src/public/Index.tsx, openbas-front/src/public/components/lessons/ExerciseViewLessons.tsx, openbas-front/src/root.tsx
=> [frontend] Fixing the back to administration button not working

openbas-api/src/main/java/io/openbas/schema/SchemaApi.java, openbas-api/src/main/java/io/openbas/search/FullTextSearchApi.java, openbas-api/src/main/java/io/openbas/search/FullTextSearchService.java, openbas-framework/src/main/java/io/openbas/utils/schema/SchemaUtils.java
* Closes https://github.com/OpenBAS-Platform/openbas/issues/1786
=> [backend] Fix unsafe Reflection

pom.xml
* Upgrade tomcat-embed-core
*
* Closes #2147 
*
=> [backend] Upgrade tomcat-embed-core

openbas-api/src/main/java/io/openbas/executors/openbas/service/OpenBASExecutorContextService.java, openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASInjector.java, openbas-api/src/main/java/io/openbas/migration/V3_55__Update_table_asset_agent_jobs.java, openbas-api/src/main/java/io/openbas/migration/V3_57__Update_table_asset_agent_jobs.java, openbas-api/src/main/java/io/openbas/rest/asset/endpoint/EndpointApi.java, openbas-api/src/main/java/io/openbas/rest/asset/endpoint/form/EndpointRegisterInput.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/service/EndpointService.java, openbas-api/src/test/java/io/openbas/utils/fixtures/AssetAgentJobFixture.java, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/AssetAgentJob.java, openbas-model/src/main/java/io/openbas/database/specification/AssetAgentJobSpecification.java
* Adapt OpenBAS backend for the next tasks related to the agents (multi traces, installation mode,...)
* Closes #2067  
3 PR in 1, need PR from agent (https://github.com/OpenBAS-Platform/agent/pull/38) and implant (https://github.com/OpenBAS-Platform/implant/pull/36) to test
=> [backend] Adapt backend on new agent logic (part 2)

openbas-model/src/main/java/io/openbas/database/model/Agent.java
=> [backend] fix threshold for agent inactivity (#2067)

openbas-api/src/main/java/io/openbas/rest/injector_contract/InjectorContractService.java, openbas-api/src/main/java/io/openbas/rest/injector_contract/output/InjectorContractOutput.java, openbas-model/src/main/java/io/openbas/database/model/InjectorContract.java
* Fix error when I apply sort on update at column:
* 
* Add update at to injectorcontractOutput
* Add queryable property to updated at
* Closes #2193 
=> [backend/frontend] Add update at param to injector contract and add queryable property

openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
* Filter out inject disables
* Issue ui not reproducible
* Closes #2041 
*
=> [frontend] Filter out injects that are not enabled or have no exposed

openbas-api/src/main/java/io/openbas/migration/V3_61__Delete_all_update_agent_asset_agent_jobs.java
=> [backend] add a migration to delete hanging agent update jobs (#2247)

openbas-api/src/main/java/io/openbas/executors/tanium/openbas-tanium-packages.json, openbas-model/src/main/java/io/openbas/database/model/InjectorContract.java, openbas-model/src/main/java/io/openbas/helper/InjectModelHelper.java
* Closes https://github.com/OpenBAS-Platform/openbas/issues/2250
=> [backend] Add default values to is ready computation

openbas-front/src/components/common/DialogApplyTagRule.tsx, openbas-front/src/components/fields/TagFieldSingle.tsx
Cosmetic changes after demo feedbacks
* disable the + in the tag field when the tag field is disabled
* align the title in DialogApplyRule
* Closes #1998
*
- [] I added/update the relevant documentation (either on github or on notion) -> doc is added in another PR
=> [backend] TagRule: Cosmetic changes after demo feedbacks Issue/1998

openbas-api/src/main/java/io/openbas/migration/V3_62__make_exercise_pause_tz_aware.java, openbas-model/src/main/java/io/openbas/helper/InjectModelHelper.java
* Correctly account for pauses in inject strat time computation
*
* Closes #2282
Tests are in another PR
=> [backend] fix pause computation in inject start date (#2282)

openbas-api/src/main/java/io/openbas/service/InjectImportService.java, openbas-api/src/main/java/io/openbas/service/utils/InjectImportUtils.java, openbas-api/src/test/java/io/openbas/service/InjectImportServiceTest.java, openbas-api/src/test/java/io/openbas/utils/mockMapper/MockMapperUtils.java
* Converting return lines to HTML tags when importing rich text fields
*
* Closes #2317 
*
=> [backend] Converting return lines to HTML tags when importing rich text fields

openbas-api/src/main/java/io/openbas/migration/V3_63__Add_agent_to_inject_expectation.java, openbas-api/src/main/java/io/openbas/migration/V3_64__Add_ExecutionTraces_table.java
Fix migration order on release branch
=> [tool] fix migration order

openbas-api/src/main/java/io/openbas/injectors/caldera/CalderaExecutor.java, openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASImplantExecutor.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-api/src/main/java/io/openbas/service/EndpointService.java, openbas-api/src/main/java/io/openbas/service/InjectExpectationService.java, openbas-api/src/main/java/io/openbas/service/InjectExpectationUtils.java, openbas-api/src/test/java/io/openbas/rest/ExpectationApiTest.java, openbas-api/src/test/java/io/openbas/rest/inject_expectation/ExpectationsExpirationManagerServiceTest.java, openbas-api/src/test/java/io/openbas/rest/inject_expectation/InjectExpectationServiceTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/ExpectationFixture.java, openbas-framework/src/main/java/io/openbas/model/expectation/DetectionExpectation.java, openbas-framework/src/main/java/io/openbas/model/expectation/ManualExpectation.java, openbas-framework/src/main/java/io/openbas/model/expectation/PreventionExpectation.java, openbas-model/src/main/java/io/openbas/database/model/InjectExpectation.java, openbas-model/src/main/java/io/openbas/database/repository/EndpointRepository.java
* Refactor creation agent expectations at executor level (extraction methods: creation expectations and creation sigantures )
* Fix filter endpoint (show only parents agents)
Tests:
Implant obas
Implant caldera
=> [backend] Refact creation expectation with clean signatures

openbas-api/src/main/java/io/openbas/injectors/email/service/EmailService.java
=> [backend]Add traces for sending emails(#2324)

openbas-front/src/admin/components/injects/InjectTestList.tsx, openbas-front/src/admin/components/injects/InjectTestReplayAll.tsx, openbas-front/src/utils/Localization.js
=> [Frontend]Correct the replay all of injects tests(#2174)

openbas-front/src/components/OrganizationField.js, openbas-front/src/components/PlayerField.js
=> [frontend] Correct color in organizations and players selectors (#2351)

openbas-api/src/main/java/io/openbas/executors/Executor.java
=> [backend] Fix status null

openbas-front/src/admin/components/lessons/scenarios/Lessons.tsx
=> [frontend] Correct in scenario lessons learned tab (#1843)

openbas-front/src/admin/components/simulations/simulation/overview/ExerciseComponent.tsx
=> [frontend] Correct spacing in simulation overview (#2173)

openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/form/InjectExecutionInput.java, openbas-api/src/test/java/io/openbas/rest/InjectApiTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/AgentFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/AgentComposer.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/EndpointComposer.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/InjectComposer.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/InjectStatusComposer.java
=> Add trace status test

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingDetail.tsx, openbas-model/src/main/java/io/openbas/database/model/Asset.java
=> [frontend/backend] search missing assets for execution details logs

openbas-front/src/components/Autocomplete.js
=> [frontend] Correctly placing label of fields with on-the-fly creation (#2349)

openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Team.java, openbas-model/src/main/java/io/openbas/database/model/User.java
* Fix some OpenAPI annotations to avoid conflict with established typescript code when regenerating the api type proxies in typescript
=> [backend] fix openapi annotations to restore compatible api types

openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-api/src/main/java/io/openbas/service/AssetGroupService.java
* Manage asset group with rules and asset added for atomic testing in pending instead of "inject executed"
=> [backend] Fix atomic testing in pending with asset group

openbas-front/src/admin/components/common/injects/form/InjectDefinition.js
* Fix issue with endpoints list in inject definition
* Contributes to #2434
=> [frontend] adapt injectdefinition with new contract of EndpointsList (#2434)

openbas-front/src/admin/components/settings/DataIngestionMenu.tsx, openbas-front/src/admin/components/settings/SecurityMenu.tsx, openbas-front/src/admin/components/settings/TaxonomiesMenu.tsx, openbas-front/src/components/common/menu/RightMenu.tsx, openbas-front/src/components/common/menu/leftmenu/LeftMenu.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/2450
=> Left menu is broken when we have an error message

openbas-front/src/components/ThemeDark.ts, openbas-front/src/components/ThemeLight.ts
* Fix a typo in the name of the font we use
*
* Closes #2445 
*
=> [frontend] fix usage of geologica

openbas-api/src/main/java/io/openbas/migration/V3_67__Update_Execution_traces_status_asset_inactive.java
* Migration for execution traces: Asset inactive 2 agent inactive
*
* Closes #1860 
*
=> [backend] Add migration traces status

openbas-api/src/main/java/io/openbas/migration/V3_66__Migrate_agents_to_same_endpoint.java
* Fix migration asset tags
* #1860 
=> [backend] Fix migration asset tags

openbas-api/src/main/java/io/openbas/service/InjectExpectationService.java, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/UpdateInjectLogicalChains.tsx
* Fix error when we re try un inject:
=> [frontend] Fix UI atomic undefined injector contract

openbas-api/src/main/java/io/openbas/rest/settings/PreviewFeature.java, openbas-api/src/main/java/io/openbas/service/InjectExpectationService.java, openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java, openbas-api/src/main/java/io/openbas/utils/ResultUtils.java, openbas-api/src/test/java/io/openbas/rest/AtomicTestingApiTest.java, openbas-api/src/test/java/io/openbas/utils/ResultUtilsTest.java
* Add feature flag to ui expectation at agent level
*
=> [backend] Add feature flag for UI agent expectations

openbas-front/src/admin/components/settings/DataIngestionMenu.tsx, openbas-front/src/admin/components/settings/SecurityMenu.tsx, openbas-front/src/admin/components/settings/TaxonomiesMenu.tsx, openbas-front/src/admin/components/settings/attack_patterns/AttackPatterns.js, openbas-front/src/admin/components/settings/data_ingestion/XlsMappers.tsx, openbas-front/src/admin/components/settings/groups/Groups.js, openbas-front/src/admin/components/settings/kill_chain_phases/KillChainPhases.js, openbas-front/src/admin/components/settings/policies/Policies.tsx, openbas-front/src/admin/components/settings/tags/Tags.js, openbas-front/src/admin/components/settings/users/Users.js, openbas-front/src/components/common/menu/RightMenu.tsx
* Improv right menu style
PS: By adding the missing doc on taxonomies, I took the opportunity to improve the style of the right menu.
=> Improve right menu style

openbas-api/src/main/java/io/openbas/export/FileExportBase.java, openbas-api/src/main/java/io/openbas/export/Mixins.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/form/InjectExportFromSearchRequestInput.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-api/src/main/java/io/openbas/service/ArticleService.java, openbas-api/src/test/java/io/openbas/rest/exercise/ExerciseApiExportTest.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectExportTest.java, openbas-api/src/test/java/io/openbas/rest/inject/service/InjectServiceTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/InjectorContractComposer.java, openbas-front/src/actions/injects/inject-action.ts, openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/utils/api-types.d.ts
* Enable correct behaviour when using the `select all` checkbox in injects list.
* Fix #2513 
=> [backend / frontend] "Select all" inject bulk export mode (#2513) 

openbas-front/src/utils/Localization.js, openbas-model/src/main/java/io/openbas/database/model/BannerMessage.java
=> [frontend] Fix "caldera executor not responding" translation

openbas-front/src/admin/components/common/injects/InjectsListButtons.tsx
* Add 8px spacing between the inject upload button and display modes toggles
* Closes #2558
=> [frontend] spacing for inject upload button

openbas-front/src/admin/components/common/injects/CreateInject.tsx
Add TTP code on inject create form
=> [frontend] add TTP code on create inject form

openbas-api/src/main/java/io/openbas/migration/V3_66__Migrate_agents_to_same_endpoint.java
* Update Migration script for:
* Asset-> expectations, asset groups, inject assets
* Recreate fk, index
*
=> [backend] Update migration

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/common/injects/status/traces/ExecutionTime.tsx
=> [frontend] align last execution date on inject

openbas-front/src/admin/Index.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroups.tsx, openbas-front/src/admin/components/simulations/simulation/AnimationMenu.tsx, openbas-front/src/admin/components/simulations/simulation/logs/Logs.js, openbas-front/src/admin/components/simulations/simulation/mails/Mails.js, openbas-front/src/admin/components/simulations/simulation/overview/SimulationComponent.tsx, openbas-front/src/admin/components/simulations/simulation/validation/Validations.js
fix style in simulation submenus
*
*
* Closes #2587 
*
=> [frontend] fix main style of admin index

openbas-api/src/main/java/io/openbas/injectors/opencti/config/OpenCTIConfig.java, openbas-api/src/main/java/io/openbas/injectors/opencti/service/OpenCTIService.java, openbas-api/src/main/resources/application.properties
* Be able to completly override openCTI api url
=> [backend] add openbas.xtm.opencti.api_url

openbas-front/src/admin/components/common/injects/form/InjectDetailsForm.tsx
* The "pristine" flag should be false when the details is already open which is the case when updating an inject. This PR will update the "prisitine" flag default value depending on the openDetails.
* Closes #2603
=> [frontend] fix bug in inject update issue/2603

openbas-front/src/admin/components/common/injects/form/InjectDetailsForm.tsx
* In the InjectDetails replacing content null with content empty as the null can cause some issue in the application.
* Closes #2605
=> [frontend] fixing creating injects with content null issue/2605

openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java, openbas-api/src/main/java/io/openbas/telemetry/OpenTelemetryConfig.java, openbas-api/src/test/java/io/openbas/config/NoOpOpenTelemetryConfig.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectApiTest.java, openbas-framework/src/main/java/io/openbas/config/OpenBASConfig.java
=> [backend] feature flag telemetry

renovate.json
* Remove useless gitea check & permit up to 10 pr concurrently to be created as we have almost always 2 or 3 renovate  prs waiting to be merged 
*
* 
*
=> [tool] Improve & clean renovate config

openbas-api/pom.xml, openbas-api/src/main/java/io/openbas/rest/report/model/ReportInjectCommentId.java, openbas-api/src/main/resources/application.properties, openbas-model/pom.xml
=> [backend] Fix warnings at backend start

openbas-api/src/main/java/io/openbas/service/ImportService.java
* Change on the exception raised to bring clearer error
*
* Closes #2623 
*
=> Change on the exception raised to bring clearer error

openbas-api/src/main/java/io/openbas/injectors/caldera/CalderaExecutor.java, openbas-api/src/main/java/io/openbas/injectors/caldera/CalderaInjector.java, openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASImplantExecutor.java, openbas-api/src/main/java/io/openbas/utils/ExpectationUtils.java, openbas-api/src/test/java/io/openbas/utils/ExpectationUtilsTest.java
* Add signature parent process name for caldera and clean up other unused signatures.
* Refact computeSignature to have a single method for both Openbas executor and Caldera executor.
Implant obas
Implant caldera
* Closes #2339 
* Linked to https://github.com/OpenBAS-Platform/openbas/issues/2331
=> [backend] Add parent process name for caldera and cs detection

openbas-front/src/admin/components/settings/ThemeForm.tsx
* Show Default value in settings 
* Closes #2464 
*
=> [frontend] Show Default value for settings

openbas-api/src/main/java/io/openbas/migration/V3_72__Add_FKs_jointure_tables_to_tags.java
* Add script to remove orphans rows in jointure tables where the referenced key no longer exists and add foreign key constraints with ON DELETE CASCADE.
* Closes #2583 
=> [backend] Add fk for jointure tables

openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java
=> [backend] avoid two threads to execute in same time implant callback

openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java
* lock implant callback thread by inject id
related to this issue https://github.com/OpenBAS-Platform/openbas/issues/2614
=> [backend] lock implant callback thread by inject id

openbas-api/src/main/java/io/openbas/migration/V3_72__Add_FKs_jointure_tables_to_tags.java
* Add annotation @Component into migration flyway
*
*
=> [backend] Add component annotation on migration

openbas-api/src/main/java/io/openbas/executors/crowdstrike/client/CrowdStrikeExecutorClient.java, openbas-api/src/main/java/io/openbas/executors/crowdstrike/service/CrowdStrikeExecutorService.java, openbas-api/src/main/java/io/openbas/service/EndpointService.java, openbas-model/src/main/java/io/openbas/database/repository/EndpointRepository.java
* Manage register for multiple endpoints with same mac address
* Add limit for Crowdstrike API (issue will be created to improve the limit)
* Closes #2672
=> [backend] Fix Crowdstrike agent registered

openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java, openbas-api/src/main/java/io/openbas/telemetry/OpenTelemetryConfig.java, openbas-api/src/test/java/io/openbas/config/NoOpOpenTelemetryConfig.java, openbas-framework/src/main/java/io/openbas/config/OpenBASConfig.java
* Removing feature flag on telemetry
* Changing the url to the correct ones 
* Closes #656 
*
=> [backend] Removing FF on telemetry and changing the url (#656)

openbas-api/src/main/java/io/openbas/rest/atomic_testing/form/InjectResultOverviewOutput.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/Index.tsx, openbas-front/src/admin/components/simulations/simulation/injects/InjectIndex.tsx, openbas-front/src/utils/api-types.d.ts
* https://prerelease.obas.staging.filigran.io/admin/atomic_testings/db474980-9595-450b-be5d-e4414b3c9f18
* ![image](https://github.com/user-attachments/assets/ec385c37-7d91-4a42-9d7e-80dfcd786fca)
*
=> [frontend] Fix injector contract paylaod null

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx
* Deduplication Expectation in frontend
*
=> [frontend] Deduplicated expectation frontend

openbas-api/src/main/java/io/openbas/config/AppSecurityConfig.java
Remove error when you trying to logout on local env.
=> Improv logout on local env

openbas-front/src/components/common/menu/leftmenu/LeftMenu.tsx, openbas-front/src/components/common/menu/leftmenu/MenuItemGroup.tsx, openbas-front/src/components/common/menu/leftmenu/MenuItemSingle.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/2723
* https://github.com/OpenBAS-Platform/openbas/issues/2724
=> [frontend] Improv UI (#2723, #2724)

openbas-front/src/admin/components/common/injects/status/traces/EndpointTraces.tsx
=> [frontend] Fix error ui related to uppercase

openbas-front/src/admin/components/assets/endpoints/Endpoints.tsx, openbas-front/src/admin/components/atomic_testings/InjectResultList.tsx, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/simulations/SimulationList.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/2460
=> Behavior of lists with 1 item is not correct (missing bottom border)

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/components/SearchFilter.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/2521
=> Wrong size of search input and bottom margin with title in atomic testing overview

pom.xml
* Upgrading spring-security-crypto
*
* Closes https://github.com/OpenBAS-Platform/security/issues/1
*
=> [backend] Upgrading spring-security-crypto

openbas-api/src/main/java/io/openbas/executors/ExecutorHelper.java, openbas-api/src/main/java/io/openbas/executors/crowdstrike/service/CrowdStrikeExecutorContextService.java
* Update the Windows encoding for the command sent to Crowdstrike to ensure the implant is not detected by Crowstrike EDR
* Closes #2653 
=> [backend] Ability to spawn an OpenBAS implant with Crowdstrike executor

openbas-api/src/main/java/io/openbas/rest/atomic_testing/form/InjectResultOverviewOutput.java, openbas-api/src/main/java/io/openbas/utils/InjectMapper.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingInformation.tsx, openbas-front/src/utils/api-types.d.ts
* First part of this https://github.com/OpenBAS-Platform/openbas/issues/2725
=> Show tag in atomic testing overview

openbas-front/src/admin/components/common/injects/form/InjectDefinition.js, openbas-front/src/admin/components/common/injects/form/InjectDetailsForm.tsx, openbas-front/src/admin/components/common/injects/form/InjectForm.js, openbas-front/src/components/fields/TagField.tsx
=> [frontend]Update inject form visual

openbas-front/src/admin/components/payloads/CreatePayload.js, openbas-front/src/admin/components/payloads/PayloadForm.tsx, openbas-front/src/admin/components/payloads/form/CommandsFormTab.tsx, openbas-front/src/components/fields/PlatformFieldController.tsx, openbas-front/src/components/fields/SelectFieldController.tsx, openbas-front/src/components/fields/TextFieldController.tsx
=> [frontend] correct UI on payload form

openbas-api/src/main/java/io/openbas/execution/ExecutionExecutorService.java, openbas-api/src/main/java/io/openbas/service/EndpointService.java
* Don't delete an agent automatically, the user must do the action himself
* Issue created (https://github.com/OpenBAS-Platform/openbas/issues/2837) to improve the traces if an agent is deleted during a payload execution
=> [Backend] Fix trace status message without agent

openbas-front/src/components/ThemeDark.ts, openbas-front/src/components/ThemeLight.ts
=> [frontend] adapt theme as opencti

openbas-api/src/main/java/io/openbas/execution/ExecutionExecutorService.java, openbas-api/src/main/java/io/openbas/executors/caldera/client/CalderaExecutorClient.java, openbas-api/src/main/java/io/openbas/executors/crowdstrike/client/CrowdStrikeExecutorClient.java, openbas-api/src/main/java/io/openbas/executors/tanium/client/TaniumExecutorClient.java, openbas-api/src/main/java/io/openbas/injectors/caldera/client/CalderaInjectorClient.java, openbas-api/src/main/java/io/openbas/injectors/opencti/service/OpenCTIService.java, openbas-api/src/main/java/io/openbas/rest/mapper/MapperApi.java
* added missing parent exception parameter when throwing new exceptions after a catch
* added missing logs in case it's not possible
* Closes #2860
=> Missing exception propagation

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingFindings.tsx, openbas-front/src/admin/components/findings/FindingList.tsx
* Create a reusable component for Findings list
* Closes #2845
=> [frontend] create reusable component for findings list

openbas-api/src/main/java/io/openbas/rest/finding/FindingUtils.java, openbas-api/src/test/java/io/openbas/rest/finding/FindingUtilsTest.java
* Fix creation findings by asset, inject and value: If asset is not linked to finding, we have to add it.
* Error (multiples agents same asset):
https://prerelease.obas.staging.filigran.io/admin/atomic_testings/77b962f3-819a-4f2d-8d41-ae92cb0d9af7/detail
=> [backend] Fix creation findings with filtering by inject, asset and value

openbas-api/src/main/java/io/openbas/executors/tanium/client/TaniumExecutorClient.java
* Filter Tanium assets from Tanium API to get only "active" assets
* If a user deletes a Tanium inactive asset, it won't come back
* Closes #2670
=> [backend] Filter Tanium assets from Tanium API to get only "active" assets

openbas-front/src/admin/components/common/injects/form/InjectDefinition.js, openbas-front/src/admin/components/common/injects/form/InjectDetailsForm.tsx, openbas-front/src/admin/components/simulations/simulation/injects/CreateQuickInject.tsx, openbas-front/src/admin/components/simulations/simulation/injects/QuickInject.js
=> [frontend] Adjust spacing in inject creation form

openbas-api/src/main/java/io/openbas/telemetry/OpenTelemetryConfig.java
* Fix on the instance creation date to send ISO_INSTANT
*
* Closes #2902 
*
=> Fix on the instance creation date to send ISO_INSTANT

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/CreateExerciseInput.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseInput.java, openbas-api/src/main/java/io/openbas/rest/exercise/form/UpdateExerciseInput.java, openbas-front/src/admin/components/simulations/simulation/ExerciseForm.tsx
* Closes https://github.com/OpenBAS-Platform/openbas/issues/2914
=> Update a simulation loose the automated trigger

openbas-front/src/admin/components/nav/LeftBar.tsx, openbas-front/src/admin/components/settings/Index.tsx
=> [frontend] Update route for parameter #2871

openbas-api/src/main/java/io/openbas/executors/Executor.java, openbas-api/src/main/java/io/openbas/executors/Injector.java, openbas-api/src/main/java/io/openbas/utils/InjectionUtils.java
* Add logs if exception "inject is too old"
* Issue not reproduced, try to extend the time to launch an inject
* Closes #2798
=> [backend] Try to fix "inject too old"

openbas-api/src/main/java/io/openbas/migration/V3_76__Add_challenge_attempt.java, openbas-api/src/main/java/io/openbas/rest/challenge/ChallengeApi.java, openbas-api/src/main/java/io/openbas/rest/challenge/response/ChallengeInformation.java, openbas-api/src/main/java/io/openbas/rest/challenge/response/ChallengeResult.java, openbas-api/src/main/java/io/openbas/service/ChallengeService.java, openbas-api/src/main/java/io/openbas/service/InjectExpectationService.java, openbas-api/src/main/java/io/openbas/service/challenge/ChallengeAttemptService.java, openbas-api/src/main/java/io/openbas/utils/ExpectationUtils.java, openbas-api/src/main/java/io/openbas/utils/challenge/ChallengeAttemptUtils.java, openbas-api/src/main/java/io/openbas/utils/challenge/ChallengeExpectationUtils.java, openbas-framework/src/main/java/io/openbas/expectation/ExpectationBuilderService.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx, openbas-front/src/admin/components/common/injects/expectations/Expectation.ts, openbas-front/src/admin/components/common/injects/expectations/ExpectationUtils.tsx, openbas-front/src/admin/components/simulations/simulation/validation/expectations/ManualExpectations.tsx, openbas-front/src/public/components/challenges/ChallengesPlayer.js, openbas-front/src/public/components/challenges/ChallengesPreview.js, openbas-front/src/public/components/channels/ChannelPlayer.js, openbas-front/src/public/components/channels/ChannelPreview.js, openbas-model/src/main/java/io/openbas/database/model/ChallengeAttempt.java, openbas-model/src/main/java/io/openbas/database/model/ChallengeAttemptId.java, openbas-model/src/main/java/io/openbas/database/repository/ChallengeAttemptRepository.java
* Closes https://github.com/OpenBAS-Platform/openbas/issues/2983
* Closes https://github.com/OpenBAS-Platform/openbas/issues/2984
* Closes https://github.com/OpenBAS-Platform/openbas/issues/2980
* Closes https://github.com/OpenBAS-Platform/openbas/issues/2981
=> [frontend] Manual validation scores are inconsistent in the screen animation > validations (#2983)

openbas-api/src/main/java/io/openbas/telemetry/OpenTelemetryConfig.java
* Making the number of nanoseconds not fixed
*
* Closes #2969 
*
=> [backend] Making the number of nanoseconds not fixed

openbas-api/src/main/java/io/openbas/execution/ExecutionExecutorService.java
* Rollback hibernate unproxy asset to endpoint for inject launched
* Closes #2961
=> [backend] Error on chaining injects traces

openbas-front/src/components/ItemTargets.tsx
=> [frontend] Use standard - for the absence of target (#2531)

openbas-api/src/main/java/io/openbas/helper/InjectHelper.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-api/src/main/resources/application.properties, openbas-model/src/main/java/io/openbas/database/model/InjectStatus.java, openbas-model/src/main/java/io/openbas/database/specification/InjectSpecification.java
* Implement a garbage collector to automatically replace pending injects in maybe prevented that have been inactive for more than 10 minutes.
* Closes #2801
* Closes #1882
=> [backend] add garbage collector on pending injects

openbas-dev/docker-compose.yml
* Added a useSVE=0 flag to elastic's JVM option to make it compatible with Apple M4
* None
=> [backend] Fix/docker compose elastic for mac m4

.github/PULL_REQUEST_TEMPLATE.md
* Add section: What should be tested and how?
*
=> [tools] Update template pr github

openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetViz.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/SecurityCoverage.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/SecurityCoverageContent.tsx
* Mitre attack widget - Options show covered TTP only is not keep when page is reload
=> [frontend] Store mitre matrix user preference

openbas-front/src/admin/components/lessons/scenarios/Lessons.tsx, openbas-front/src/admin/components/scenarios/scenario/lessons/ScenarioLessons.tsx, openbas-front/src/admin/components/simulations/simulation/lessons/SimulationLessons.tsx
=> [frontend] Fix Preview lesson learned

openbas-front/src/admin/components/common/challenges/ChallengeCard.tsx, openbas-front/src/admin/components/common/challenges/ContextualChallenges.js, openbas-front/src/public/components/challenges/ChallengesPlayer.js, openbas-front/src/public/components/challenges/ChallengesPreview.js
=> [frontend] create ChallengeCard component

openbas-front/src/admin/components/assets/endpoints/endpoint/AgentList.tsx
=> [frontend] Fix undefined executor (#2838)

openbas-api/src/main/java/io/openbas/rest/settings/PreviewFeature.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/utils.ts
* Hide target pagination behind feature flag
Edit application.properties and add or modify:
```java
openbas.enabled_dev_features=TARGET_PAGINATION
``` 
* Contributes to #2663
=> [frontend] enable feature flag for target pagination (#2663)

openbas-front/src/admin/components/assets/endpoints/endpoint/Endpoint.tsx
* Add scroll bar
* Closes #3084 
*
=> [frontend] Add scroll bar to list of ips/mac in the endpoint overview

openbas-front/src/components/AppThemeProvider.tsx
=> [frontend] fix theme selector (#2793)

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java, openbas-api/src/main/java/io/openbas/rest/inject/exports/InjectsFileExport.java, openbas-api/src/main/java/io/openbas/rest/payload/PayloadUtils.java
=> [backend] import output parser

openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboard.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardHeader.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardPopover.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboards.tsx
=> Add custom dashboard header

openbas-front/src/admin/components/Dashboard.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingHeader.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingTabs.tsx, openbas-front/src/admin/components/common/injects/ResponsePie.tsx, openbas-front/src/admin/components/simulations/simulation/injects/InjectIndexHeader.tsx, openbas-front/src/admin/components/simulations/simulation/injects/InjectIndexTabs.tsx, openbas-front/src/admin/components/simulations/simulation/overview/SimulationComponent.tsx
=> [frontend] Improve header and response pie style in inject overview (#1984)

openbas-model/src/main/java/io/openbas/database/raw/RawFinding.java, openbas-model/src/main/java/io/openbas/database/repository/FindingRepository.java, openbas-model/src/main/java/io/openbas/engine/model/finding/EsFinding.java, openbas-model/src/main/java/io/openbas/engine/model/finding/FindingHandler.java, openbas-model/src/main/java/io/openbas/service/EsService.java
* Fix link findings scenarios
*
* 
*
=> [backend] Fix link findings/scenarios

openbas-api/src/main/java/io/openbas/execution/ExecutionExecutorService.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java
* Fix pending injects when only inactive agents are set
=> [backend] Fix pending injects for inactive agents

openbas-front/src/actions/Schema.js
* https://github.com/OpenBAS-Platform/openbas/issues/3136
=> Page "Simulation > Animation > Mails" is not available

README.md
* Update link telemetry
* delete section openstreetmap
* Fix label reference:  "beginner friendly issue"-> "good first issue"
=> [tool] Update readme

openbas-front/src/admin/components/components/teams/TeamPlayers.tsx
* Fix crash when open teams drawer on definition tab due to latency on store loading
=> [frontend] Fix crash on definition team

openbas-front/package.json, openbas-front/src/utils/api-types.d.ts, openbas-front/yarn.lock
=> [dependencies] Upgrade swagger typescript api 13.1.3

openbas-front/src/admin/components/common/injects/ResponsePie.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistribution.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionByInjectorContract.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreByInject.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreByOrganization.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreByPlayer.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreByTeam.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreByTeamInPercentage.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreOverTimeByInjectorContract.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreOverTimeByTeam.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistributionScoreOverTimeByTeamInPercentage.tsx, openbas-front/src/admin/components/simulations/simulation/reports/SimulationReportPage.tsx, openbas-front/src/admin/components/simulations/simulation/reports/getExerciseReportPdfDoc.ts, openbas-front/src/admin/components/simulations/simulation/reports/useExerciseReportData.ts, openbas-front/src/components/Empty.js, openbas-front/src/components/ExportPdfButton.tsx
=> Fix : Report is not displayed correclty 

openbas-api/src/main/java/io/openbas/rest/finding/FindingUtils.java, openbas-api/src/test/java/io/openbas/rest/finding/FindingUtilsTest.java, openbas-front/src/admin/components/payloads/PayloadForm.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/ContractOutputType.java
* Add CVE finding type
1. Back-end only, waiting nuclei for the E2E tests
* Closes https://github.com/OpenBAS-Platform/openbas/issues/3157
=> Add CVE finding type

openbas-api/src/main/java/io/openbas/rest/settings/PreviewFeature.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/utils.ts
Remove the feature flag to enable the pagination on release 1.17 onwards
=> [frontend/backend] remove pagination flag lock

openbas-front/src/admin/components/common/injects/status/traces/EndpointTraces.tsx, openbas-front/src/admin/components/common/injects/status/traces/TraceMessage.tsx
* Fix overflow in endpoint traces
Before:
Now
1. Execute an atomic testing 
2. Check layout of traces
* Closes #3187 
*
=> [frontend] Fix overflow in traces

openbas-front/src/admin/components/common/injects/Injects.tsx
* Reintroduce the tags filter for Injects in scenario and simulation screens
1. Create a scenario
2. Add a few injects
3. Set various tags on the injects
4. Use the dropdown "Tags" filter to filter the injects
5. Start a simulation from the scenario
6. Navigate to the simulation injects definition list (third tab)
7. repeat step 4
* Closes #3032
=> [frontend] reenable tags filter in injects list (#3032)

openbas-front/src/actions/Schema.js, openbas-front/src/admin/components/components/teams/TeamPlayers.tsx, openbas-front/src/admin/components/scenarios/scenario/teams/teamContextForScenario.ts, openbas-front/src/admin/components/simulations/simulation/teams/teamContextForExercise.ts
=> [frontend] fix team update when players update in definition tab (#3199)

openbas-api/src/main/java/io/openbas/rest/atomic_testing/AtomicTestingApi.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java
* New decorators to document some API usage and types
*
=> [backend] add openapi docs to new endpoints (#2663)

openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-api/src/test/java/io/openbas/scheduler/jobs/InjectsExecutionJobTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/InjectComposer.java
* Avoiding parallel launch of parent/children
*
1. Create 3 injects and chains them together
2. Using the timeline, make them only a few seconds apart
3. Launch the simulation
4. Make sure they don't start at the same time but one at each new loop
* 
*
=> [backend] Avoiding parallel launch of parent/children

.github/workflows/test-feature-branch.yml
The deployment of feature branches deployment has been switched from dev cluster to staging.
This PR is just in order to update displayed URL at the end of the workflow.
https://github.com/FiligranHQ/platform/issues/905
- [x ] I consider the submitted work as finished
- [x ] I tested the code for its functionality
=> [CI] Feature branch staging

openbas-front/src/admin/components/common/injects/CreateInject.tsx
=> [frontend] fix create inject layout

openbas-front/src/admin/components/payloads/PayloadForm.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/PayloadArgument.java, openbas-model/src/main/java/io/openbas/database/model/PayloadPrerequisite.java
Error from :
https://www.notion.so/filigran/Test-session-Milestone-1-17-2008fce17f2a80838344cda5259a571e?p=2008fce17f2a80ba8611d4aad29f2651&pm=s
=> [frontend/backend] fix payload form

openbas-front/src/admin/components/scenarios/scenario/ScenarioHeader.tsx
=> [frontend] update scenario assistant button border color

openbas-front/src/admin/components/scenarios/scenario/ScenarioAssistantDrawer.tsx
Update border color of the Select TTPs button
=> [frontend] update select TTP button border color

openbas-api/src/main/java/io/openbas/rest/helper/RestBehavior.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectAssistantService.java
Link to issue 2449
Fix : error when the group was empty
=> [backend] fix empty group case

openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/AssetGroup.java, openbas-model/src/main/java/io/openbas/database/model/Team.java
* Fis perf issue introduced by serialising injects for Team and AssetGroup entities
1. Snappy endpoints !
=> [backend] remove injects serialisation from asset group and team

openbas-api/src/main/java/io/openbas/rest/injector_contract/InjectorContractService.java, openbas-model/src/main/java/io/openbas/database/model/InjectorContract.java
* Closes https://github.com/OpenBAS-Platform/openbas/issues/3391
=> [backend] Injector contract: fill default value based on cardinality

openbas-front/src/components/ThemeDark.ts
=> [frontend] Review scrollbar color with theme dark (#3092)

openbas-front/src/reducers/Referential.ts, openbas-front/src/store.ts
=> [frontend] Clear store on logout (#1807)

openbas-front/src/admin/components/atomic_testings/InjectResultList.tsx, openbas-front/src/components/common/queryable/filter/useRetrieveOptions.tsx, openbas-front/src/components/common/queryable/filter/useSearchOptions.tsx, openbas-front/src/utils/lang/en.json, openbas-front/src/utils/lang/fr.json, openbas-front/src/utils/lang/zh.json, openbas-model/src/main/java/io/openbas/database/model/Inject.java
* https://github.com/OpenBAS-Platform/openbas/issues/3340
=> Add attack pattern filter on inject results

.drone.yml
=> [ci] Add Drone runner name

.drone.yml
* Fix display drone runner host
*
=> [Improvement] Fix display drone runner host

openbas-api/src/main/java/io/openbas/rest/attack_pattern/AttackPatternApi.java, openbas-api/src/main/java/io/openbas/rest/attack_pattern/form/AttackPatternUpsertInput.java, openbas-api/src/main/java/io/openbas/service/ImportService.java, openbas-front/src/utils/api-types.d.ts
* [backend] Handle more simple import of payloads for testing
=> [backend] Handle more simple import of payloads for testing

openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/HistogramParameters.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetForm.tsx, openbas-front/src/utils/api-types-custom.d.ts, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/lang/en.json, openbas-front/src/utils/lang/fr.json, openbas-front/src/utils/lang/zh.json, openbas-model/src/main/java/io/openbas/engine/api/StructuralHistogramWidget.java, openbas-model/src/main/java/io/openbas/engine/model/attackpattern/AttackPatternHandler.java, openbas-model/src/main/java/io/openbas/service/EsService.java
* Change representative on TTPs
* Linked to https://github.com/OpenBAS-Platform/openbas/issues/3340
=> [backend] Change attack pattern representative

openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java
Add logs to updateFinalInjectStatus to debug
=> [backend] Add logs to updateFinalInjectStatus to debug

openbas-model/src/main/java/io/openbas/database/repository/VulnerableEndpointRepository.java
* Fix counts in active/inactive agents in vulnerable enpoints list dimension
* Related #2885
*
=> [backend] fix counts for active agents (#2885)

openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/FilterFieldBaseEntity.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetCreationSeries.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetCreationSeriesList.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetForm.tsx, openbas-front/src/utils/lang/en.json, openbas-front/src/utils/lang/fr.json, openbas-front/src/utils/lang/zh.json
* Select at least one dimension to create a widget
=> [frontend] select at least one dimension widget

openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetCreationSecurityCoverageSeries.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetUtils.tsx
* Fix : update simulation on attack paths widget
=> [frontend] fix update simulation on attack path widget

openbas-api/src/test/java/io/openbas/rest/custom_dashboard/CustomDashboardApiTest.java, openbas-api/src/test/java/io/openbas/rest/custom_dashboard/CustomDashboardWidgetApiTest.java, openbas-api/src/test/java/io/openbas/rest/dashboard/DashboardApiTest.java, openbas-api/src/test/java/io/openbas/rest/finding/FindingApiTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/CustomDashboardFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/CustomDashboardParameterFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/WidgetFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/CustomDashboardComposer.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/CustomDashboardParameterComposer.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/InjectComposer.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/WidgetComposer.java, openbas-model/src/main/java/io/openbas/database/model/CustomDashboard.java, openbas-model/src/main/java/io/openbas/database/model/CustomDashboardParameters.java, openbas-model/src/main/java/io/openbas/database/repository/CustomDashboardParametersRepository.java
* Add a test to validate basic functionality of the param binding from dashboard to widget
* Contributes #3330 
=> [backend] add test coverage for entities param binding functionality (#3330)

openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/attack_paths/AttackPath.tsx
* reduce columns on attack paths widget
=> [frontend] reduce gap between columns

openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/HorizontalBarChart.tsx
* Click on horizontal bar is enabled only if the bar is for the simulation we have selected
1. Make a custom dashboard with the param attack pattern and your simulation
2. Go to the simulation and click on a bar, you are redirected to the inject list with a filter
=> [frontend] Click enabled in horizontal bar only for simulation selected

openbas-front/src/admin/components/components/teams/TeamPlayers.tsx
* Align list header and contents
1. Go on player team list (scenario or simulation page)
2. Check if the header is aligned to the list content. 
=> [frontend] Add method to enable player in team (#3445)

openbas-front/src/admin/components/simulations/simulation/overview/SimulationComponent.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/HorizontalBarChart.tsx, openbas-front/src/components/common/queryable/uri/useUriState.tsx
fix for add anchor in horizontal bar chart click
=> [frontend] fix for add anchor in horizontal bar chart click

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java
* Fic import paylaod single
*
1. Modify paylaod with remediation
2. Export
3. Import 
4. check remediations
*
=> [backend] Fix import payload (#3171)

openbas-model/src/main/java/io/openbas/database/raw/RawInjectIndexing.java, openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java, openbas-model/src/main/java/io/openbas/engine/model/inject/InjectHandler.java
* Take into account the updated at of the injectorContract for the Inject indexation
=> [backend] fix es synchro on inject

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java, openbas-api/src/main/java/io/openbas/rest/inject/service/ExecutableInjectService.java, openbas-api/src/main/java/io/openbas/rest/payload/exports/PayloadFileExport.java, openbas-api/src/main/java/io/openbas/rest/payload/service/PayloadExportService.java, openbas-api/src/main/java/io/openbas/service/ImportEntry.java, openbas-api/src/main/java/io/openbas/service/ImportService.java, openbas-front/src/admin/components/payloads/form/PayloadArgumentsField.tsx, openbas-front/src/components/fields/DocumentField.tsx, openbas-model/src/main/java/io/openbas/database/model/Payload.java
* Add document payload argument to allow local downloading in implant instead of internet
* Closes #3556
=> Add document payload argument to allow local downloading in implant instead of internet (#3556)

openbas-api/src/main/java/io/openbas/executors/Executor.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java
* Delete logs used to understand an issue
* Closes #2797
=> [backend] Delete debug logs (#2797)

openbas-api/src/main/java/io/openbas/rest/inject/form/InjectExecutionInput.java, openbas-api/src/main/java/io/openbas/rest/inject/service/ExecutableInjectService.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectExecutionService.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java, openbas-api/src/main/java/io/openbas/service/InjectExpectationService.java, openbas-api/src/test/java/io/openbas/rest/InjectExpectationTraceApiTest.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectApiTest.java, openbas-api/src/test/java/io/openbas/service/InjectExpectationServiceTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/InjectExpectationFixture.java, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/InjectExpectationSignature.java
* add start and end date signatures
* Closes #3359
=> [backend] add start and end date signatures

openbas-front/src/admin/components/scenarios/scenario/ScenarioPopover.tsx
* Fix inverted args in export handler
1. Locate or create Scenario with assigned Teams in the Definition tab
2. Export scenario with selecting only the "with teams" option
3. Reimport scenario: teams are correctly assigned (no players in any of them)
* Closes #3689 
=> [frontend] handle export args correctly in scenario export (#3689)

openbas-api/src/main/java/io/openbas/rest/inject/service/InjectExecutionService.java
* replaced slf4j template with string.format
- [] I added/update the relevant documentation (either on github or on notion)
=> [backend] fix: fixed logs where variables where not substituted

openbas-front/src/admin/components/Dashboard.tsx, openbas-front/src/utils/Charts.ts
=> [frontend] Improve vertical bar chart style (#3649)

openbas-api/src/main/java/io/openbas/rest/asset/endpoint/form/EndpointRegisterInput.java, openbas-api/src/main/java/io/openbas/rest/executor/ExecutorApi.java, openbas-api/src/main/java/io/openbas/service/EndpointService.java, openbas-api/src/test/java/io/openbas/rest/EndpointApiTest.java, openbas-front/src/utils/api-types.d.ts
* [backend] Allow customizable installation path for agents
* Closes #3740
=> [backend] Allow customizable installation path for agents (#3740)

openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx, openbas-front/src/admin/components/common/injects/expectations/Expectation.ts
* Fix expectation types for steps:
1. Create an inject with expectations prev, dete, manual
#3648 
=> [frontend] Fix expectation types for steps (#3648)

openbas-api/src/main/java/io/openbas/service/RoleService.java, openbas-api/src/test/java/io/openbas/service/RoleServiceTest.java, openbas-model/src/main/java/io/openbas/database/model/Capability.java
* Adding the concept "parent" in the capability enum so we can force the fact that when you add a "MANAGE" cap you will also get the "ACCESS" capa. It is already enforced in the front
* Closes #3722 
* #375 
- [NA] I added/update the relevant documentation (either on github or on notion)
- [NA] For bug fix -> I implemented a test that covers the bug
=> [backend] Issue/375 RBAC Capa hierarchy 

openbas-front/src/components/common/queryable/pagination/PaginationComponentV2.tsx
* Check if the total pages is inferior or equals to the current page
1. Go on payload, on the second page
2. Filter on source="filigran" 
3. You are supposed to be redirect on the first page if you have less than one page of filigran's source
* Closes #3755 
*
=> [frontend] Filtering by source is not working in payloads

openbas-api/src/main/java/io/openbas/service/PermissionService.java, openbas-api/src/test/java/io/openbas/service/PermissionServiceTest.java, openbas-front/package.json, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Action.java, openbas-model/src/main/java/io/openbas/database/model/Capability.java
* adding the capa "create assessment" to allow creation of scenarion/simulation
1.  call the api to create a scenario with or without the capa
* #375 
*
- [NA] I added/update the relevant documentation (either on github or on notion)
- [NA] For bug fix -> I implemented a test that covers the bug
=> [backend] RBAC adding create assesment capa Issue/375 

openbas-api/src/test/java/io/openbas/rest/DocumentApiTest.java, openbas-api/src/test/java/io/openbas/rest/PayloadApiSearchTest.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectImportTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/PayloadFixture.java, openbas-front/src/admin/components/payloads/CreatePayload.js, openbas-front/src/admin/components/payloads/PayloadForm.tsx, openbas-front/src/admin/components/payloads/PayloadPopover.js, openbas-front/src/admin/components/payloads/Payloads.tsx, openbas-front/src/admin/components/payloads/form/CommandsFormTab.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Executable.java
cherry pick from #3697 
close #3425
=> [frontend] Impossible to create a payload of type executable file

openbas-front/src/admin/components/scenarios/scenario/ScenarioPopover.tsx, openbas-front/src/admin/components/settings/groups/GroupPopover.js, openbas-front/src/admin/components/settings/groups/Groups.js, openbas-front/src/components/common/ButtonPopover.tsx, openbas-front/src/root.tsx, openbas-front/src/utils/permissions/PermissionsProvider.tsx, openbas-front/src/utils/permissions/ability.ts, openbas-front/src/utils/permissions/parserRbac.ts, openbas-front/src/utils/permissions/types.ts
* Parse the grant to make casl rules 
*
* Closes #3782
*
=> [frontend] Add Grant in the CASL logic (#3782)

openbas-api/src/main/java/io/openbas/rest/statistic/StatisticApi.java, openbas-api/src/main/java/io/openbas/service/PermissionService.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectApiTest.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectExportTest.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectImportTest.java, openbas-api/src/test/java/io/openbas/service/PermissionServiceTest.java, openbas-dev/Frontent start.run.xml, openbas-model/src/main/java/io/openbas/database/model/AssetGroup.java, openbas-model/src/main/java/io/openbas/database/model/AttackPattern.java, openbas-model/src/main/java/io/openbas/database/model/Capability.java, openbas-model/src/main/java/io/openbas/database/model/Collector.java, openbas-model/src/main/java/io/openbas/database/model/Cve.java, openbas-model/src/main/java/io/openbas/database/model/Group.java, openbas-model/src/main/java/io/openbas/database/model/Inject.java, openbas-model/src/main/java/io/openbas/database/model/Injector.java, openbas-model/src/main/java/io/openbas/database/model/InjectorContract.java, openbas-model/src/main/java/io/openbas/database/model/KillChainPhase.java, openbas-model/src/main/java/io/openbas/database/model/Organization.java, openbas-model/src/main/java/io/openbas/database/model/Role.java, openbas-model/src/main/java/io/openbas/database/model/Tag.java, openbas-model/src/main/java/io/openbas/database/model/TagRule.java
* open taxonomies apis
* check parent permission for injects
* add resourceType missing
* link new resource type to capa
*  -> to fix the login I had to open two apis /api/statictics and /api/settings but they should not be open so I created a bug to follow up https://github.com/OpenBAS-Platform/openbas/issues/3789
1. create a user with no admin right and play with the api
* Closes #3748
- [NA] I added/update the relevant documentation (either on github or on notion)
- [NA] For bug fix -> I implemented a test that covers the bug
=> [backend] RBAC new permission logic Issue/3748

openbas-front/src/admin/components/common/injects/status/ExecutionStatusDetail.tsx
*Typo error change PLAYER to PLAYERS
1.Create atomic email with some users/players
2.Execute inject
3.You should have logs from users
* Closes #3728
=> [frontend] Fix Execution logs players missing (#3728)

openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java
* Fixing a NPE causing a crash of injectors
*
1. Create an nmap injector
2. Add an agentless endpoint in the injector
3. Launch it
* Closes https://github.com/OpenBAS-Platform/injectors/issues/87
*
=> [backend] Fixing a NPE causing a crash of injectors (#87)

openbas-api/src/main/java/io/openbas/App.java, openbas-api/src/test/java/io/openbas/AppTest.java, openbas-framework/src/main/java/io/openbas/config/OpenBASConfig.java
* Adding possibility to provide instance ID
*
1. Delete your instance_id in the parameters database
2. Start openbas
3. The id should have been recreated with a generated UUID as well as the creation date
1. Add an UUID to the property openbas.instance-id in application.properties
2. Start openbas
3. The id should have been updated with the provided UUID as well as the creation date
* Closes #3644 
*
=> [backend] Adding possibility to provide instance ID (#3644)

openbas-api/src/main/java/io/openbas/executors/caldera/service/CalderaExecutorService.java, openbas-api/src/main/java/io/openbas/rest/asset/endpoint/EndpointApi.java, openbas-api/src/main/java/io/openbas/rest/asset/endpoint/form/EndpointInput.java, openbas-api/src/main/java/io/openbas/service/EndpointService.java, openbas-front/src/admin/components/assets/endpoints/EndpointForm.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Endpoint.java, openbas-model/src/main/java/io/openbas/database/repository/EndpointRepository.java
* [backend] Support endpoints without IP addresses
* Closes #3868
=> [backend] Support endpoints without IP addresses (#3868)

openbas-api/src/main/java/io/openbas/service/GrantService.java
* inverted two paramteres in the new hasgrant function
=> [backend] RBAC mvp2 - fix mistake

openbas-api/src/main/java/io/openbas/service/EndpointService.java, openbas-front/src/admin/components/assets/endpoints/EndpointsDialogAdding.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx, openbas-front/src/admin/components/common/endpoints/fragments/EndpointAgentsExecutorsFragment.tsx, openbas-front/src/admin/components/payloads/Payloads.tsx, openbas-front/src/admin/components/simulations/simulation/reports/getExerciseReportPdfDoc.ts, openbas-front/src/utils/lang/en.json, openbas-front/src/utils/lang/fr.json, openbas-front/src/utils/lang/zh.json
* [backend/frontend] Hide deprecated payloads by default
* Closes #3882
=> [backend/frontend] Hide deprecated payloads by default (#3882)

openbas-api/src/main/java/io/openbas/service/EndpointService.java
* [backend] Fix tags loading in lazy loading
* Closes #3884
=> [backend] Fix tags loading in lazy loading (#3884)

openbas-front/src/admin/components/settings/ParametersOnboardingForm.tsx
* Closes https://github.com/OpenBAS-Platform/openbas/issues/3886
=> [frontend] Fix something is updating each time you're going to the settings page

openbas-api/src/main/resources/application.properties
* Trace connection leaks on prerelease
*
* 
*
To be removed once the leak has been found and plugged.
=> [backend] Trace connection leaks on prerelease

openbas-api/src/main/java/io/openbas/rest/document/DocumentApi.java
* Remove old document Apis old permission logic to only keep RBAC
*
1. Create a user with only the capa to access the document
2. With the admin user create a doc assigned to a scenario
3. Log-in with the user and go to the document screen -> you should see the doc
* #375
*
- [] I added/update the relevant documentation (either on github or on notion)
=>  [backend] RBAC: remove doc old logic Issue/375

openbas-front/src/admin/components/common/injects/UpdateInject.tsx
* The field are disabled if we do NOT have manage permissions
1. Login as admin
2. Check if you are able to edit an inject
*
=> [frontend] RBAC - Fix inject form

openbas-api/src/main/java/io/openbas/rest/inject_test_status/ScenarioInjectTestApi.java, openbas-api/src/main/java/io/openbas/rest/inject_test_status/SimulationInjectTestApi.java, openbas-front/src/actions/asset_groups/assetgroup-helper.d.ts, openbas-front/src/admin/components/common/ToolBar.js, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/scenarios/scenario/injects/ScenarioInjects.tsx, openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx
* Fetch asset groups from scenario or exercise if we do not have asset right
1. Log in with user granted on some scenario/simulations (manage) but without asset capa
2. Go on simulation / inject 
3. Check the checkbox of one inject
4. You shouldn't have 401
=> [frontend] RBAC - Fix select inject

.drone.yml, openbas-dev/docker-compose.yml
Upgrade minio in CI to RELEASE.2025-06-13T11-33-47Z
=> Upgrade minio in CI to RELEASE.2025-06-13T11-33-47Z

openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/expectations/InjectExpectations.tsx, openbas-front/src/admin/components/common/injects/form/InjectContentForm.tsx
* Update the condition to see the "add expectations" button depending on capabilities
1. Go to Atomic Testing
2. Select Send Individual Email
3. Try to add an expectation to the test
* Closes #3957
=> [frontend] RBAC - Add expectations was unavailable

openbas-api/src/main/java/io/openbas/migration/V4_29__Add_default_roles.java
* Add default roles
* Admin: Bypass capa
* Observer: all ACCESS capa except for Platform Settings capas
* Manager: all capa except for Platform Settings capas and Bypass
1. Run the migration and verify that the roles are created with the correct capa 
* Closes #3991
* #375 
=> [backend] RBAC: default roles Issue/3991

openbas-front/src/admin/components/common/injects/expectations/InjectExpectations.tsx
=> [frontend] Prevent crash when editing an inject with empty expectations

openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardWrapper.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/form/ParametersTab.tsx, openbas-front/src/components/fields/AutocompleteField.tsx
=> [frontend] Fix dashboard parameters saving (#3172)

openbas-api/src/main/java/io/openbas/rest/stream/StreamApi.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/ScenarioExecutionJob.java
* Disabling concurrent job for the simulation creation
* Better copy of variable into a newly created simulation as it seems to be taking a lot of CPU usage
1. Test recurring jobs with variable to check if they are created and have all their variables
* Closes #4034
*
=> [backend] Stability improvement

openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/form/InjectForm.tsx, openbas-front/src/admin/components/common/injects/form/articles/InjectAddArticles.tsx, openbas-front/src/admin/components/common/injects/form/articles/InjectArticlesList.tsx, openbas-front/src/admin/components/common/injects/form/challenges/InjectAddChallenges.tsx, openbas-front/src/admin/components/common/injects/form/challenges/InjectChallengesList.tsx, openbas-front/src/admin/components/common/injects/form/teams/InjectAddTeams.tsx, openbas-front/src/admin/components/common/injects/form/teams/InjectTeamsList.tsx, openbas-front/src/admin/components/common/injects/utils.ts, openbas-front/src/components/common/SelectList.tsx
* Add the teams as default values 
* Make the difference between create mode and update mode :
-  **create mode** we reset the default values as much as we click on injector contract : it has to fill the field in the inject form.
- **update mode** the default values are reset when the component is mounted. 
* When we create a team in the inject form, it's automatically assigned to the simulation you are working on
1. Go on simulation / inject tab 
2. Try to create a new inject : should be 🆗 
3. Go on media inject 
4. Try to update a team : should be 🆗 
5. Try to create a team : should appears in the definition tabs
6. Try to update the email subject : should be 🆗 
7. Play with the different sections where inject are
If this is a relatively large or complex change, kick off the discussion …
=> [frontend] Fix inject form

openbas-api/src/main/java/io/openbas/service/ScenarioToExerciseService.java, openbas-api/src/main/java/io/openbas/service/VariableService.java, openbas-model/src/main/java/io/openbas/database/repository/VariableRepository.java
* Improve the copy of variable to ease the load on the CPU
*
1. Have a recurring scenario with variable
2. Check they still are created in the recurring simulations
* 
*
=> [backend]Improve variable request

openbas-front/src/root.tsx
…
* for xtmhub connectivity check, check the /health endpoint to avoid font errors in the front end
1. set `openbas.xtm.hub.url=https://dev.hub.staging.filigran.io/`
2. login on openbas, and check there is no font errors in the console.
* Closes #4036
=> [frontend] - feature(xtmhub/airgapped): check health endpoint to avoid font errors

openbas-api/src/main/java/io/openbas/collectors/expectations_expiration_manager/service/ExpectationsExpirationManagerService.java, openbas-api/src/main/java/io/openbas/service/InjectExpectationService.java
* Adding support of paged request in Expectations Expiration Manager
*
* 
*
=> [backend] Adding support of paged request in Expectation Manager

openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/configuration/WidgetSeriesSelection.tsx, openbas-front/src/components/common/queryable/filter/FilterChipPopoverInput.tsx
* Add scenario filter options loader on widget creation
=> [frontend] add loader on widget serie filter field

openbas-front/src/admin/components/assets/asset_groups/AssetGroupManagement.tsx, openbas-front/src/components/common/Drawer.tsx, openbas-front/src/components/common/menu/leftmenu/LeftMenu.tsx
* Fix this behavior -> There is no size limit for the findings title
=> [frontend] Improv header drawer style

openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardCreation.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardPopover.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/customDashboardUtils.ts
* Fix update default dashboards from dashboard page
=> [frontend] fix update default dashboard from dashboard page

openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java
* detach entities to try to fix optimistic lock error
*
We were not able to reproduce the issue on local/feature env, but we can check it still works.
Register on xtmhub, check there is no error
Reload filgran experience page to make a connectivity check and ensure there is no error
Unregister xtmhub, check there is no error
* Closes #3958
=> [backend] fix: optimistic lock error - detach entities

openbas-front/src/admin/components/common/ToolBar.js
* Fix injects bulk update display
1. Go to a scenario injects tab
2. Select 2 or more injects
3. On the toolbar, clic on update (pencil icon)
4. Options lines should be displayed as usual
Before the fix : 
After the fix :
=> [frontend] Fix injects update bulk display

openbas-api/src/main/java/io/openbas/api/xtmhub/XtmHubApi.java, openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java
Native delete works. let's add again RBAC and remove manual transactions.
*
*
We were not able to reproduce the issue on local/feature env, but we can check it still works.
1.Register on xtmhub, check there is no error
2.Reload filgran experience page to make a connectivity check and ensure there is no error
3.Unregister xtmhub, check there is no error
* Closes #3958 
*
=> [backend] fix: optimistic lock error - clean up code

openaev-api/src/main/java/io/openaev/migration/V4_41__Update_Collectors_Name.java
* Fix on renaming collectors name
*
* 
*
=> [backend] Fix on migration to rename collectors

openaev-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardParameters.tsx, openaev-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardWrapper.tsx, openaev-front/src/admin/components/workspaces/custom_dashboards/widgets/configuration/common/TimeRangeUtils.tsx
* Set to undefined the dashboard if you remove it
* Fix error in console
1. Navigate to the Scenario → Analysis tab
2. Add a dashboard
3. The dashboard should appear
4. Remove the dashboard
5. The dashboard should disappear
=> [frontend] Remove dashboard in simulation or scenario

openaev-api/src/main/java/io/openaev/rest/user/PlayerApi.java, openaev-api/src/main/java/io/openaev/rest/user/PlayerService.java, openaev-api/src/test/java/io/openaev/rest/user/PlayerServiceTest.java
* Compare the user and the player to know if we do the update or not
1. Call upsertPlayer with identical input → no update
2. Call with modified fields → update
=> [backend] Compare player and user for the update

openaev-front/src/admin/components/components/teams/TeamPopover.tsx, openaev-front/src/components/common/DialogDelete.tsx
* Adding a loader on delete buttons
*
*
*
=> [frontend] Adding a loader on delete buttons

openaev-front/src/utils/lang/en.json, openaev-front/src/utils/lang/fr.json, openaev-front/src/utils/lang/zh.json
* Fix github urls in onboarding page : FR, ZN and EN
1. Go to page onboarding and test links for slack and github
=> [frontend] Fix github urls in onboarding page

openaev-api/src/main/java/io/openaev/utils/ExpectationUtils.java, openaev-api/src/test/java/io/openaev/rest/inject_expectation/ExpectationsExpirationManagerServiceTest.java, openaev-api/src/test/java/io/openaev/utils/fixtures/ExpectationFixture.java
* Add filter for assetgroups in expectations utils to avoid: 
1. Create an inject with asset groups and assets and expectations
2. You can validate expectation in the ui or wait for expired manager 
3. Check any errors
=> [backend] Fix npe in expectation utils (#3870)
