OpenAEV-Platform/openaev

openex-front/src/admin/components/exercises/injects/InjectDefinition.js, openex-front/src/components/ThemeLight.js, openex-front/src/utils/Localization.js
* https://github.com/OpenEx-Platform/openex/issues/344
=> [frontend] Add error message on FieldArray

openex-api/pom.xml
Try to upgrade flyway to remove this warning message : 
Flyway upgrade recommended: PostgreSQL 16.0 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 14.
For now, I am stuck with this version. I keep digging.
Ressources :
https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html
=> [api] Upgrade flyway dependency to 9.0.3

openbas-front/src/admin/components/settings/users/Users.js
https://github.com/OpenBAS-Platform/openbas/issues/892
=> [frontend]Fix users list header

openbas-api/src/main/java/io/openbas/rest/document/DocumentApi.java, openbas-model/src/main/java/io/openbas/database/raw/RawDocument.java, openbas-model/src/main/java/io/openbas/database/repository/DocumentRepository.java
*
*
*
*
- [x ] I consider the submitted work as finished
- [x ] Where necessary I refactored code to improve the overall quality
=> [backend] add query to fetch documents

openbas-api/src/main/java/io/openbas/helper/RabbitMQHelper.java, openbas-api/src/main/java/io/openbas/rest/settings/PlatformSettingsApi.java, openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java, openbas-api/src/main/resources/application.properties, openbas-framework/src/main/java/io/openbas/config/RabbitmqConfig.java, openbas-front/src/admin/components/settings/Parameters.tsx, openbas-front/src/utils/api-types.d.ts
close #841 
based on work by @Dimfacion
=> [backend/frontend] get rabbitmq version and fix value in frontend

openbas-api/src/main/java/io/openbas/opencti/OpenCTIApi.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/main/java/io/openbas/utils/ResultUtils.java, openbas-model/src/main/java/io/openbas/database/repository/ScenarioRepository.java
OpenCTI should get the latest ended simulation based on scenarios instead of the latest simulation based on the first scenario.
* https://github.com/OpenBAS-Platform/openbas/issues/1047
*
- Generate a scenario from OpenCTI to OpenBAS
- Launch a simulation with some expectations
- Wait for the end of this simulation
- Go to opencti and checked that the security posture is the same as that on OpenBAS
- Re launch the simulation, change the expectation result and verify the new posture in both platform
OpenCTI PR -> https://github.com/OpenCTI-Platform/opencti/pull/7233
=> [backend] Change external reference resolution for OpenCTI integration

openbas-api/src/main/java/io/openbas/rest/challenge/ChallengeApi.java, openbas-api/src/main/java/io/openbas/rest/challenge/ChallengeHelper.java, openbas-api/src/main/java/io/openbas/rest/challenge/ExerciseChallengeApi.java, openbas-api/src/main/java/io/openbas/rest/challenge/ScenarioChallengeApi.java, openbas-api/src/main/java/io/openbas/rest/challenge/output/ChallengeOutput.java, openbas-model/src/main/java/io/openbas/database/model/Challenge.java, openbas-model/src/main/java/io/openbas/database/model/ChallengeFlag.java, openbas-model/src/main/java/io/openbas/database/specification/InjectSpecification.java
https://github.com/OpenBAS-Platform/openbas/issues/898
=> [backend] Improv performance on challenges

openbas-api/src/main/java/io/openbas/rest/channel/ChannelApi.java, openbas-api/src/main/java/io/openbas/rest/channel/ChannelHelper.java, openbas-api/src/main/java/io/openbas/rest/channel/ExerciseArticleApi.java, openbas-api/src/main/java/io/openbas/rest/channel/ScenarioArticleApi.java, openbas-api/src/main/java/io/openbas/rest/channel/output/ArticleOutput.java, openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-model/src/main/java/io/openbas/database/model/Article.java, openbas-model/src/main/java/io/openbas/database/specification/ArticleSpecification.java, openbas-model/src/main/java/io/openbas/database/specification/InjectSpecification.java
https://github.com/OpenBAS-Platform/openbas/issues/898
=> [backend] Improv performance on articles

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java, openbas-api/src/main/java/io/openbas/migration/V3_16__Add_array_union_agg_method.java, openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/exports/ExerciseExportMixins.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/team/TeamApi.java, openbas-api/src/test/java/io/openbas/importer/V1_DataImporterTest.java, openbas-api/src/test/resources/importer-v1/import-data.json, openbas-front/src/admin/components/common/articles/Articles.tsx, openbas-front/src/admin/components/components/teams/TeamPopover.tsx, openbas-front/src/admin/components/simulations/simulation/articles/ExerciseArticles.tsx, openbas-model/src/main/java/io/openbas/database/raw/RawPaginationTeam.java, openbas-model/src/main/java/io/openbas/database/repository/ChallengeRepository.java, openbas-model/src/main/java/io/openbas/database/repository/OrganizationRepository.java, openbas-model/src/main/java/io/openbas/database/repository/TagRepository.java, openbas-model/src/main/java/io/openbas/database/repository/TeamRepository.java
* https://github.com/OpenBAS-Platform/openbas/issues/1067
=> [backend/frontend] Fix import

openbas-api/src/main/java/io/openbas/search/FullTextSearchService.java, openbas-api/src/main/java/io/openbas/utils/pagination/PaginationUtils.java, openbas-front/src/admin/components/nav/TopBar.tsx, openbas-model/src/main/java/io/openbas/database/specification/SpecificationUtils.java
* Fixing the wrong indicators
* Adding a way to search for an id
* Fixing the search bar not updating when going on the search from a url 
* #1017 
*
=> [frontend/backend] Fixing full text search wrong indicators

openbas-front/src/admin/components/common/injects/Injects.js, openbas-front/src/admin/components/scenarios/scenario/Index.tsx, openbas-front/src/admin/components/simulations/ImportUploaderExercise.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseDateForm.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseHeader.tsx, openbas-front/src/components/i18n.js, openbas-front/src/utils/Localization.js
* Hide the possibility to show timeline
* Align date display on scenario header based on simulation header
* Align color button on scenario header based on simulation header
* Fix simulation start date edition when we switch from scheduled to manual with an error on date
* Reload simulations page on import
=> [frontend] Last fix before release

openbas-api/src/main/java/io/openbas/config/OpenBASSaml2AuthenticationRequestRepository.java
* Fixing random login errors
*
* #647 
*
This needs to be tested extensively ... The fix is to prevent the callback of the SAML Provider to recreate an HttpSession if the previous one is older than 120s.
=> [backend] Fixing random login errors

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java
=> [backend] fix null pointer

openbas-model/src/main/java/io/openbas/database/model/User.java
* Make the admin property filterable
*
* issue #1132 
*
=> [backend] Make the admin property filterable

openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-model/src/main/java/io/openbas/database/model/Inject.java
=> [backend] fix null pointer exc

openbas-front/src/admin/components/nav/LeftBar.tsx
* Move scenarios with simulations and AT in the menu
*
* issue #1056 
*
=> [frontend] Move scenarios with simulations and AT in the menu

openbas-front/src/admin/components/scenarios/scenario/ScenarioDistributionByExercise.tsx, openbas-front/src/utils/Charts.js
=> [Frontend]Scenario scores display

openbas-api/src/main/java/io/openbas/service/AtomicTestingService.java, openbas-model/src/main/java/io/openbas/database/criteria/InjectCriteria.java
* Small change to fix the count in atomic testing
*
*
*
=> [backend] Fix on count in atomic testing search

openbas-front/src/admin/components/common/injects/CreateInject.tsx
* Validate when contracts maps is null, empty or undefined
*
* https://github.com/OpenBAS-Platform/openbas/issues/1121
*
=> [backend] Validate contracts undefined, null or empty (#1121)

openbas-front/src/actions/Schema.js, openbas-front/src/admin/components/atomic_testings/InjectList.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingDetail.tsx
*
* https://github.com/OpenBAS-Platform/openbas/issues/1141
*
=> [frontend] fix crash page atomic testing after deleting a payload

openbas-front/src/admin/components/common/form/TextFieldAskAI.tsx
*
*
* https://github.com/OpenBAS-Platform/openbas/issues/1126
*
=> [frontend] Fix options for tone in message (#1126)

openbas-api/src/main/java/io/openbas/rest/atomic_testing/AtomicTestingApi.java, openbas-api/src/main/java/io/openbas/service/AtomicTestingService.java, openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx
* Dynamic assets are added into asset group: all machine (depending on filter):
* ![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/716aca35-8fef-4c4c-8afc-ef6f7af6cd4b)
* ![image](https://github.com/OpenBAS-Platform/openbas/assets/4162296/cddb00f0-6e59-4ef4-8797-6ee3fbd059a9)
* https://github.com/OpenBAS-Platform/openbas/issues/1055
*
=> [backend] Add dynamic assets as children in group asset if applicable (#1055)

openbas-api/src/main/java/io/openbas/injectors/email/service/EmailService.java
The current mechanism allows us to make three attempts to store messages in the imap.
But by setting the traces to error, the status changes to partial, even if after the third attempt the storage is done.
By passing the trace into info, we make sure to keep the status close to reality.
=> [backend] Change trace level when store message in imap

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java, openbas-api/src/main/java/io/openbas/rest/payload/PayloadApi.java, openbas-api/src/main/java/io/openbas/service/AtomicTestingService.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/main/java/io/openbas/utils/Constants.java, openbas-framework/src/main/java/io/openbas/executors/tanium/service/TaniumExecutorService.java, openbas-framework/src/main/java/io/openbas/integrations/PayloadService.java, openbas-framework/src/main/java/io/openbas/utils/StringUtils.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingHeader.tsx, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/simulations/simulation/ExercisePopover.tsx
* https://github.com/OpenBAS-Platform/openbas/issues/1233
=> [backend/frontend] Fix duplicate payload

openbas-api/src/main/java/io/openbas/executors/caldera/service/CalderaExecutorService.java, openbas-api/src/main/java/io/openbas/injectors/email/service/ImapService.java, openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java, openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java, openbas-front/src/public/components/systembanners/SystemBanners.tsx, openbas-front/src/utils/Localization.js, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/utils.ts, openbas-model/src/main/java/io/openbas/database/model/BannerMessage.java, openbas-model/src/main/java/io/openbas/database/model/SettingKeys.java
=> [frontend/backend] Adding platform messages if imap is not reachable

openbas-api/src/main/java/io/openbas/service/ScenarioToExerciseService.java
* https://github.com/OpenBAS-Platform/openbas/issues/1286
=> [backend] Fix inject content when create simulation from scenario

openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/output/InjectOutput.java, openbas-front/src/actions/Inject.js, openbas-front/src/actions/injects/Inject.d.ts, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/common/injects/Injects.js, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/InjectStatus.java
=> Adding Test inject in scenario and simulations

openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx, openbas-front/src/admin/components/simulations/simulation/validation/expectations/DetectionPreventionExpectationsValidationForm.tsx, openbas-front/src/components/fields/SecurityPlatformField.tsx
* Remove security platform already set in expectation creation
* Disable edition of security platform in expectation edition
* https://github.com/OpenBAS-Platform/openbas/issues/1181
*
=> In atomic testing, update the manual set expectation, the security platform is not filled after full reload (and crashes if removed)

openbas-api/src/main/java/io/openbas/rest/exception/ImportException.java, openbas-api/src/main/java/io/openbas/rest/helper/RestBehavior.java, openbas-api/src/main/java/io/openbas/rest/mapper/MapperApi.java, openbas-api/src/main/java/io/openbas/rest/mapper/export/MapperExportMixins.java, openbas-api/src/main/java/io/openbas/rest/mapper/form/ExportMapperInput.java, openbas-api/src/main/java/io/openbas/rest/mapper/form/ImportMapperAddInput.java, openbas-api/src/main/java/io/openbas/rest/mapper/form/ImportMapperUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/mapper/form/InjectImporterAddInput.java, openbas-api/src/main/java/io/openbas/rest/mapper/form/InjectImporterUpdateInput.java, openbas-api/src/main/java/io/openbas/service/MapperService.java, openbas-api/src/test/java/io/openbas/service/MapperServiceExportTest.java, openbas-api/src/test/java/io/openbas/service/MapperServiceTest.java, openbas-front/src/actions/mapper/mapper-actions.ts, openbas-front/src/actions/mapper/mapper.ts, openbas-front/src/admin/components/settings/data_ingestion/ImportUploaderMapper.tsx, openbas-front/src/admin/components/settings/data_ingestion/XlsMapperPopover.tsx, openbas-front/src/admin/components/settings/data_ingestion/XlsMappers.tsx, openbas-front/src/admin/components/settings/data_ingestion/xls_mapper/MapperForm.tsx, openbas-front/src/admin/components/settings/data_ingestion/xls_mapper/RulesContractContent.tsx, openbas-front/src/admin/components/settings/data_ingestion/xls_mapper/XlsMapperUpdate.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/ImportMapper.java, openbas-model/src/main/java/io/openbas/database/model/InjectImporter.java
* Adding the ability to import/export mappers
*
* #1260 
*
=> [frontend/backend]Adding the ability to import/export mappers

openbas-api/src/main/java/io/openbas/rest/mapper/MapperApi.java, openbas-api/src/main/java/io/openbas/rest/mapper/form/ExportMapperInput.java, openbas-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx, openbas-front/src/admin/components/settings/data_ingestion/XlsMapperPopover.tsx, openbas-front/src/utils/Localization.js, openbas-front/src/utils/api-types.d.ts
…port
* Add message info
* Modify file name of mapper exports
*
*
=> [frontend]  Add info message of starting date mandatory on scenario

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/main/java/io/openbas/service/ScenarioToExerciseService.java, openbas-api/src/main/java/io/openbas/service/TeamService.java, openbas-api/src/main/java/io/openbas/utils/CopyObjectListUtils.java, openbas-api/src/test/java/io/openbas/service/ExerciseServiceTest.java, openbas-api/src/test/java/io/openbas/service/ScenarioServiceTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/ExerciseFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/ScenarioFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/TeamFixture.java, openbas-model/src/main/java/io/openbas/database/repository/TeamRepository.java
- Create new contextual team while duplicating scenario
=> [backend] fix contextual team while duplicating scenario #1303

openbas-api/src/main/java/io/openbas/rest/injector_contract/InjectorContractApi.java, openbas-api/src/main/java/io/openbas/rest/injector_contract/InjectorContractService.java, openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-api/src/main/resources/application.properties, openbas-api/src/test/resources/application.properties, openbas-front/src/admin/components/settings/data_ingestion/xls_mapper/RulesContractContent.tsx, openbas-front/src/utils/Localization.js
In XLS mapper, having a way to map "All teams" as targets of injects
* In XLS mapper, having a way to map "All teams" as targets of injects
* Make sure we have the import available on startup using a failsafe
* #1248 
*
=> [frontend/backend] In XLS mapper, having a way to map "All teams" as targets of injects

openbas-front/package.json, openbas-front/src/admin/components/simulations/simulation/ExerciseDateForm.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseDatePopover.tsx, openbas-front/src/utils/Localization.js
=> [frontend] fix simulation start time validation (#1360)

openbas-api/src/main/java/io/openbas/service/ExerciseExpectationService.java, openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx, openbas-model/src/main/java/io/openbas/database/model/InjectExpectation.java
issue :
https://github.com/OpenBAS-Platform/openbas/issues/1350
=> [backend/frontend] fix expectation status when updating score

openbas-api/pom.xml, openbas-api/src/main/resources/application.properties
* Avoid deadlocks during Flyway migrations* : https://www.notion.so/filigran/Archives-adeedfa0afb3492fbb2cbdd9a9ed23c9
* https://github.com/OpenBAS-Platform/openbas/issues/1361
* Migration spring boot 3.2.0, flyway 9.22.3 (default)
* Flyway migration : https://www.notion.so/filigran/Technical-Process-pains-8f5546790ee34fb9a8a7118d49cf24d1
=> [backend] fix deadlock flyway migration on 9.22.3

openbas-model/src/main/java/io/openbas/database/model/Team.java
* Add property sortabele to team_name: Error : Uncaught (in promise) 
Object { status: 500, timestamp: "2024-09-09T07:51:37.558+00:00", error: "Internal Server Error", path: "/api/teams/search" }
*
*
*
=> [backend] Add sortable property to team_name

openbas-front/src/admin/components/assets/asset_groups/AssetGroups.tsx, openbas-front/src/admin/components/components/teams/Teams.tsx, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/settings/attack_patterns/AttackPatterns.js, openbas-front/src/admin/components/settings/groups/Groups.js, openbas-front/src/admin/components/settings/users/Users.js, openbas-front/src/admin/components/teams/Organizations.tsx, openbas-model/src/main/java/io/openbas/database/model/Asset.java, openbas-model/src/main/java/io/openbas/database/model/Group.java, openbas-model/src/main/java/io/openbas/database/model/ImportMapper.java, openbas-model/src/main/java/io/openbas/database/model/LessonsTemplate.java, openbas-model/src/main/java/io/openbas/database/model/Mitigation.java, openbas-model/src/main/java/io/openbas/database/model/Team.java, openbas-model/src/main/java/io/openbas/database/model/User.java
=> [backend/frontend] Add missing sortable

openbas-api/src/main/java/io/openbas/rest/exception/AlreadyExistingException.java, openbas-api/src/main/java/io/openbas/rest/helper/RestBehavior.java, openbas-api/src/main/java/io/openbas/rest/team/TeamApi.java, openbas-front/src/utils/Action.js, openbas-model/src/main/java/io/openbas/database/repository/TeamRepository.java
* https://github.com/OpenBAS-Platform/openbas/issues/1398
=> [backend/frontend] Fix team creation

openbas-api/src/main/java/io/openbas/migration/V3_33__Add_Index_inject.java
* Add new indexes to speed up SQL Join
* https://github.com/OpenBAS-Platform/openbas/issues/1184
=> Atomic testing list is slow on demo environment 

openbas-api/src/main/java/io/openbas/rest/attack_pattern/AttackPatternApi.java, openbas-api/src/main/java/io/openbas/rest/injector/InjectorApi.java, openbas-api/src/main/java/io/openbas/rest/kill_chain_phase/KillChainPhaseApi.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java, openbas-api/src/main/java/io/openbas/rest/tag/TagApi.java, openbas-front/src/components/common/queryable/filter/FilterChipPopoverInput.tsx, openbas-front/src/components/common/queryable/filter/useRetrieveOptions.tsx, openbas-front/src/components/common/queryable/filter/useSearchOptions.tsx
- Problem: Filters show only 10 random entries
- Should show all entries
- Should be ordered alphabetically
=> [backend/frontend] Filters options should not be limit to 10

openbas-front/src/admin/components/assets/asset_groups/DynamicAssetField.tsx
Asset group Bug - Dynamic asset filter empty, i see ‘no option’ in the dropdown when creating a new asset group
=> [frontend] Fix missing filter on dynamic asset group

openbas-front/src/admin/components/assets/asset_groups/DynamicAssetField.tsx, openbas-front/src/utils/Localization.js
=> [frontend] change wording for dynamic asset filter

openbas-front/src/admin/components/atomic_testings/atomic_testing/Index.tsx
* When we update an element of an atomic testing, the commands lines disappear. The update object is not the same object as the get object so we re-fetch again the object to fix the bug. This page will be improved in the future.
=> [frontend] Keep commands lines shown if another element is updated in atomic testing page

openbas-front/src/admin/components/common/matrix/MitreMatrix.tsx, openbas-front/src/admin/components/common/matrix/MitreMatrixDummy.tsx
Close #1435 
- Remove experimental attributes since non compatible with Firefox
Before (Firefox):
After (Firefox):
=> [frontend] Fix Mitre Att&ck Coverage display on Firefox

openbas-model/src/main/java/io/openbas/database/criteria/GenericCriteria.java
* Add distinct on pagination to avoir duplicate result and have a good counting
Here, the result and the count is not aligned
=> [backend] Fix wrong count for pagination

openbas-front/src/admin/components/common/injects/Injects.tsx
=> [frontend]Fix the display of the result of injects bulk deletion

openbas-front/src/admin/components/components/teams/AddTeams.tsx
* Fix teamsIds state fater delete a team (when all users were activated)
*
* https://github.com/OpenBAS-Platform/openbas/issues/1516
=> [frontend] update teamsIds state

openbas-front/src/components/common/Drawer.tsx
* Just add space logic in Drawer like we do on leftbar, topbar, ect
Before
After
=> [frontend] Added space to avoid banner goes over the drawer title

openbas-api/src/main/java/io/openbas/migration/V3_41__Update_constraint_on_delete_cascade.java, openbas-model/src/main/java/io/openbas/database/model/InjectImporter.java
* Modify constraint on delete for inject importers ans rule attributs
* After modification on injectorService l77, when we make a deletebyId, I found a fk error :  
=> [backend] fix constraint on delete set null to cascade

openbas-api/src/main/java/io/openbas/executors/caldera/service/CalderaExecutorService.java, openbas-framework/src/main/java/io/openbas/integrations/ExecutorService.java
=> [backend] clean caldera settings if executor is not enable

openbas-api/src/main/java/io/openbas/injectors/email/service/ImapService.java, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/components/teams/ContextualTeams.tsx, openbas-front/src/admin/components/components/teams/UpdateTeams.tsx, openbas-front/src/admin/components/scenarios/scenario/teams/ScenarioTeams.tsx, openbas-front/src/admin/components/scenarios/scenario/variables/ScenarioVariables.tsx, openbas-front/src/admin/components/simulations/simulation/teams/ExerciseTeams.tsx, openbas-front/src/admin/components/simulations/simulation/variables/ExerciseVariables.tsx, openbas-front/src/utils/Action.ts
* https://github.com/OpenBAS-Platform/openbas/issues/1581
=> Improve latency on endpoint teams

openbas-api/src/main/java/io/openbas/schema/SchemaApi.java
* When an user is not admin, allow him to see pages with filters (like scenarios and simulations)
=> [backend] Fix 401 when user not admin and go to page with filters

openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-front/src/actions/Inject.js, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts
* Add other endpoint to bulk update in order to just update properties available on bulk update.
*
* Closes #https://github.com/OpenBAS-Platform/openbas/issues/1627 
*
=> [backend/frontend] fix bulk update injects

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java, openbas-api/src/main/java/io/openbas/rest/inject/ExerciseInjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/ScenarioInjectApi.java, openbas-api/src/main/java/io/openbas/rest/injector_contract/InjectorContractService.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/scenario/utils/ScenarioUtils.java, openbas-api/src/main/java/io/openbas/rest/user/PlayerService.java, openbas-api/src/main/java/io/openbas/service/AtomicTestingService.java, openbas-api/src/main/java/io/openbas/service/InjectService.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/main/java/io/openbas/service/TeamService.java, openbas-api/src/main/java/io/openbas/utils/pagination/PaginationUtils.java, openbas-api/src/main/java/io/openbas/utils/pagination/SearchUtilsJpa.java, openbas-framework/src/main/java/io/openbas/utils/FilterUtilsJpa.java, openbas-framework/src/main/java/io/openbas/utils/JpaUtils.java
* Use join map to avoid duplicate join
* https://github.com/OpenBAS-Platform/openbas/issues/1583
Query without filters:
```
select
distinct s1_0.scenario_id,
s1_0.scenario_name,
s1_0.scenario_severity,
s1_0.scenario_category,
s1_0.scenario_recurrence,
s1_0.scenario_updated_at,
array_remove(array_agg(t1_0.tag_id), null),
array_union_agg(ic1_0.injector_contract_platforms) 
from
scenarios s1_0 
left join
scenarios_tags t1_0 
on s1_0.scenario_id=t1_0.scenario_id 
left join
injects i1_0 
on s1_0.scenario_id=i1_0.inject_scenario 
left join
injectors_contracts ic1_0 
on ic1_0.injector_contract_id=i1_0.inject_injector_contract 
where
1=1 
and 1=1 
group by
1 
order by
6 desc 
offset
? rows 
fetch
first ? rows only
```
Query with filters: category + kill chain phases + tags
```
select
distinct …
```
=> [backend] Use join map to avoid duplicate join

openbas-api/src/main/java/io/openbas/injectors/channel/ChannelExecutor.java, openbas-front/src/admin/components/common/injects/UpdateInjectDetails.js, openbas-front/src/admin/components/scenarios/scenario/injects/ScenarioInjects.tsx, openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx, openbas-front/src/admin/components/simulations/simulation/injects/QuickInject.js, openbas-front/src/admin/components/simulations/simulation/variables/AvailableVariablesDialog.tsx
* Fix url for **Manage custom variables** on scenario, exercise, quick inject and atomic testing
* On atomic testing page : Currently, we dont have the option for custom variables :
* On scenario, exercise, we redirect to /definition for **Manage the custom variables** : 
* Closes #1473 
*
=> [frontend] Fix uri definition variables

openbas-front/src/admin/components/common/injects/InjectDefinition.js
=> [frontend] fix endpoint deletion in an inject (#1668)

openbas-front/src/admin/components/common/injects/CreateInjectDetails.js
* Fixing default value of payload argument not set up when the inject content block is not open
*
* Closes #1666 
*
=> [frontend] Fixing default value of payload argument not set up

openbas-front/src/components/common/queryable/pagination/PaginationComponentV2.tsx, openbas-front/src/components/common/queryable/uri/useUriState.tsx, openbas-front/src/components/common/queryable/useQueryableWithLocalStorage.tsx, openbas-front/src/utils/hooks/useDataLoader.js
=> [frontend] Remove duplicate requests for pagination & filters

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseImportApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java, openbas-api/src/main/java/io/openbas/rest/exercise/service/ExerciseService.java, openbas-api/src/main/java/io/openbas/rest/report/ReportApi.java, openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioExerciseApi.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/test/java/io/openbas/rest/ExerciseLessonsApiTest.java, openbas-api/src/test/java/io/openbas/rest/InjectApiTest.java, openbas-api/src/test/java/io/openbas/rest/ReportApiTest.java, openbas-api/src/test/java/io/openbas/service/ExerciseServiceTest.java, openbas-api/src/test/java/io/openbas/service/ScenarioServiceTest.java, openbas-model/src/main/java/io/openbas/database/repository/ExerciseRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ExerciseTeamUserRepository.java, openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java, openbas-model/src/main/java/io/openbas/database/repository/LessonsCategoryRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ScenarioRepository.java, openbas-model/src/main/java/io/openbas/database/repository/ScenarioTeamUserRepository.java, openbas-model/src/main/java/io/openbas/database/repository/TeamRepository.java, openbas-model/src/main/java/io/openbas/database/repository/UserRepository.java
Closes #1521 
*
*
* https://github.com/OpenBAS-Platform/openbas/issues/1521
*
=> [backend/frontend] Fix removing a team from the context doesn't work

openbas-api/src/test/java/io/openbas/rest/InjectApiTest.java
=> [backend] Inject creation/update in a simulation (#1485)

openbas-front/src/admin/Index.tsx, openbas-front/src/admin/components/atomic_testings/InjectDtoList.tsx, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/simulations/ExerciseList.tsx
* Tags are used in almost all the app so fetch them at the "top" of the Front app to get them everywhere
* Update the link for item exercises lists to not render all the page when acceding an item
* Closes #1610
=> [frontend] Fix tags displayed and links to item exercises lists (#1610)

openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java
=> [backend] Fix param to retrieve asset groups from a raw map

openbas-api/src/main/java/io/openbas/rest/helper/TeamHelper.java, openbas-api/src/main/java/io/openbas/rest/team/TeamApi.java, openbas-model/src/main/java/io/openbas/database/model/TeamSimple.java, openbas-model/src/main/java/io/openbas/database/repository/TeamRepository.java
=> [backend] Fix raw teams request (#1704)

openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java
* Handle inject with no injector contract
* Closes #1586
=> [backend] Simulations never ends if no inject / disabled injects / deleted injects (#1586)

openbas-api/src/main/java/io/openbas/rest/document/DocumentApi.java, openbas-front/src/admin/components/components/documents/DocumentPopover.js, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/raw/RawPaginationDocument.java, openbas-model/src/main/java/io/openbas/database/repository/SecurityPlatformRepository.java
* Prevent users from deleting SP logos (#1660)
*
* Closes #1660 
*
=> [backend/frontend] Prevent users from deleting SP logos (#1660)

openbas-api/src/main/resources/application.properties, openbas-framework/src/main/java/io/openbas/expectation/ExpectationPropertiesConfig.java
* Add validation for score between 0-100 for openbas.expectation.manual.default-score-value property
*
=> [backend] Add validation for default score value

openbas-api/src/main/java/io/openbas/rest/helper/RestBehavior.java, openbas-api/src/main/java/io/openbas/rest/user/UserApi.java, openbas-front/src/admin/Index.tsx, openbas-front/src/admin/components/nav/TopBar.tsx, openbas-front/src/private/components/nav/TopBar.tsx, openbas-front/src/root.tsx, openbas-front/src/utils/Action.ts
Close : #1778 
The user creation functionality worked correctly. 
However, the issue was when clicking the logout button: the page displayed the login form, but the URL did not update accordingly.
Moreover i update the status code in the back 
when a user is connected but don't have access the api return 404
when a user is not connected anymore and want to have access to some information the api return 401
=> [frontend/backend] correct logout redirection

openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASImplantExecutor.java, openbas-model/src/main/java/io/openbas/database/model/InjectExpectationSignature.java
Add matching on process parent name to be more accurate when we match prevention & detection expectation.
Linked to https://github.com/OpenBAS-Platform/collectors/pull/48
=> [backend] Add matching on parent process name for inject expectation signature

Dockerfile_ga, openbas-api/pom.xml, openbas-model/pom.xml
* Upgrading dependencies
*
* Closes #1771
* Closes #1772 
* Closes #1775 
=> [backend] Updating dependencies

openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/InjectDependencyConditions.java
* Properly generate types for chaining injects
*
* 
*
=> [backend/frontend] Properly generate types for chaining injects

openbas-front/src/admin/components/Dashboard.tsx, openbas-front/src/admin/components/atomic_testings/InjectDtoList.tsx, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/scenarios/scenario/Scenario.tsx, openbas-front/src/admin/components/simulations/ExerciseList.tsx, openbas-front/src/admin/components/simulations/Exercises.tsx, openbas-front/src/admin/components/simulations/simulation/overview/ExerciseDistribution.tsx, openbas-front/src/components/PaginatedListLoader.tsx, openbas-front/src/components/common/queryable/filter/FilterChips.tsx
Add skeleton loader on simulations/scenarios/atomic testings lists
Fix issues with filters height & loading in simulation overview
=> [frontend] add skeleton loader on main lists (#1409)

openbas-model/src/main/java/io/openbas/database/model/ExecutionStatus.java, openbas-model/src/main/java/io/openbas/database/model/InjectStatus.java
=> [backend] Fix enum comparison on inject status

openbas-front/src/admin/components/atomic_testings/InjectResultList.tsx
=> [frontend] Delete actions are not allowed on the injectresult list

openbas-api/src/main/java/io/openbas/migration/V3_48__Set_Payload_source_as_community_and_deprecate.java, openbas-api/src/main/java/io/openbas/rest/payload/PayloadApi.java, openbas-api/src/main/java/io/openbas/rest/payload/form/PayloadsDeprecateInput.java, openbas-api/src/test/java/io/openbas/rest/PayloadApiTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/PayloadInputFixture.java, openbas-framework/src/main/java/io/openbas/integrations/PayloadService.java, openbas-front/src/admin/components/payloads/PayloadPopover.js, openbas-front/src/admin/components/payloads/Payloads.tsx, openbas-front/src/utils/Localization.js, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Payload.java, openbas-model/src/main/java/io/openbas/database/repository/PayloadRepository.java
- Migration: Set payload source as `COMMUNITY` if from a collector, instead of `MANUAL`
- Migration: Set status as `DEPRECATED` when community payload was updated before the update of the collector (proposed interval: one week)
- Set a Payload as `DEPRECATED` when not processed by the Collector
* Closes https://github.com/OpenBAS-Platform/collectors/issues/46
- https://github.com/OpenBAS-Platform/collectors/pull/52
- https://github.com/OpenBAS-Platform/client-python/pull/39
=> [backend/frontend] Some payloads coming from Atomic Red team are marked as "Manual"

openbas-api/src/main/java/io/openbas/utils/InjectUtils.java
https://github.com/OpenBAS-Platform/openbas/issues/1903
=> [backend] Fix NoSuchBeanDefinitionException in retrieving command line

openbas-api/src/main/java/io/openbas/collectors/expectations_expiration_manager/service/ExpectationsExpirationManagerService.java, openbas-api/src/main/java/io/openbas/rest/expectation/ExpectationApi.java, openbas-api/src/main/java/io/openbas/rest/inject/form/InjectExpectationUpdateInput.java, openbas-framework/src/main/java/io/openbas/inject_expectation/InjectExpectationService.java, openbas-framework/src/main/java/io/openbas/inject_expectation/InjectExpectationUtils.java, openbas-model/src/main/java/io/openbas/database/model/InjectExpectationResult.java
Change strategy level of validation on the Sentinel collector side.
Objective: Sentinel is validated by the fact that an expectation has been validated by Defender. He therefore refers to him to validate his expectations.
The Defender collector fills a metadata property containing the alert ID which validated the expectation.
Sentinel looks for this alert ID in its logs to validate its expectations.
https://github.com/OpenBAS-Platform/openbas/issues/1685
=> [backend] Allowing metadata to inject expectation result

openbas-api/src/main/java/io/openbas/rest/kill_chain_phase/KillChainPhaseApi.java, openbas-api/src/test/java/io/openbas/killChainPhase/KillChainPhaseApiTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/KillChainPhaseFixture.java
* Update the order of the KillChainPhase returned by **/api/kill_chain_phases/options** to be ordered by phase order instead of alphabetical order
* Closes  [1662](https://github.com/OpenBAS-Platform/openbas/issues/1662)
=> [backend] update kill chain phase options api to sort by order

openbas-front/src/admin/components/payloads/CreatePayload.js, openbas-front/src/admin/components/payloads/PayloadForm.tsx, openbas-front/src/admin/components/payloads/PayloadPopover.js
* Further changes requested after demo:
> Hello du coup j'ai un peu regarder, si on veut avoir une logique qui ne sera pas à retoucher plus tard, mieux serait de cacher la complexité en laissant la possibilité d'avoir un champ vide, on pourrait donc appliquer les regles suivantes:
>  
> Pour le cleanup:
> Si il y a  command mais pas d'executor: error message + impossible de sauver le payload
> Si pas de command mais un executor de définit: possibilité de sauver mais le clean up executor est reset to "null" 
> Et pas de modif visible dans l'UI 
> 
* Closes #1621 
* Related #1825 
=> [frontend] Payload - Enforce required cleanup command AND executor when choosing one of the two (#1621)

openbas-api/src/main/java/io/openbas/rest/scenario/form/ScenarioInput.java
=> [backend] Delete notblank annotation

openbas-front/src/admin/Index.tsx, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/components/challenges/Challenges.js, openbas-front/src/admin/components/components/documents/Documents.js, openbas-front/src/admin/components/nav/LeftBar.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioHeader.tsx, openbas-front/src/admin/components/search/useEntityLink.tsx, openbas-front/src/admin/components/simulations/ExerciseList.tsx, openbas-front/src/admin/components/simulations/simulation/AnimationMenu.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts, openbas-front/src/admin/components/simulations/simulation/ExerciseCreation.tsx, openbas-front/src/admin/components/simulations/simulation/ExerciseHeader.tsx, openbas-front/src/admin/components/simulations/simulation/ExercisePopover.tsx, openbas-front/src/admin/components/simulations/simulation/Index.tsx, openbas-front/src/admin/components/simulations/simulation/challenges/ExerciseChallenges.tsx, openbas-front/src/admin/components/simulations/simulation/controls/CreateControl.tsx, openbas-front/src/admin/components/simulations/simulation/definition/ExerciseControlComChecks.tsx, openbas-front/src/admin/components/simulations/simulation/definition/ExerciseControlDryRuns.tsx, openbas-front/src/admin/components/simulations/simulation/definition/ExerciseSettings.tsx, openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx, openbas-front/src/admin/components/simulations/simulation/injects/InjectIndex.tsx, openbas-front/src/admin/components/simulations/simulation/injects/QuickInject.js, openbas-front/src/admin/components/simulations/simulation/mails/Mails.js, openbas-front/src/admin/components/simulations/simulation/overview/Exercise.tsx, openbas-front/src/admin/components/simulations/simulation/reports/ExerciseReportPage.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
=> [frontend] change app routing /exercises to /simulations (#1940)

openbas-api/src/main/java/io/openbas/rest/injector/InjectorApi.java, openbas-model/src/main/java/io/openbas/database/model/Executable.java, openbas-model/src/main/java/io/openbas/database/model/Payload.java
* Handle errors for executable payload like command line payload
* Closes #1897 
This PR is linked with an implant PR
=> [backend] Handle errors for payloads

openbas-front/src/admin/components/common/injects/UpdateInject.tsx
-  On Inject update, empty of predefined expectations since they are no needed if all the expectations where removed by the user
* Closes #1714 
=> [frontend] After deleting all expectations from a technical/media/challenge inject, an expectation is added by default to inject again

openbas-api/src/main/java/io/openbas/rest/inject/service/ExecutableInjectService.java
Fix this problem : 
Instantiating a `cmd `variable and using it in the same line doesn't work as expected. 
For example, the command 
```
set x=test & echo %x%
``` 
won't display the value of x because the variable hasn't been instantiated yet. To fix this, you can use the command 
```
cmd /v /c "set x=test & echo !x!"
``` 
which enables delayed variable expansion, allowing the variable to be properly referenced
In this PR i replace the %test% by !test!
In this PR https://github.com/OpenBAS-Platform/implant/pull/26 i add the  /v arguments
* Related to this issue https://github.com/OpenBAS-Platform/openbas/issues/1604
=> [backend] handle cmd variables

.circleci/config.yml, .drone.yml, openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASInjector.java, openbas-api/src/main/java/io/openbas/rest/executor/ExecutorApi.java, openbas-api/src/main/java/io/openbas/rest/injector/InjectorApi.java, openbas-api/src/main/resources/application.properties, openbas-framework/src/main/java/io/openbas/asset/EndpointService.java
* Add build & deploy for prerelease when merging on release/*
* Add a way to fetch latests/prelease agents/implants when on testing/prerelease
* Closes #1909 
*
=> [tool] update drone & circle for prerelease platform (#1909)

openbas-api/src/main/java/io/openbas/rest/payload/PayloadUtils.java
* Fix a build failure in branch
=> [backend] fix (build): use correct interface to PayloadCreateInput with PayloadUtils

openbas-api/src/test/java/io/openbas/scheduler/jobs/ScenarioExecutionJobTest.java
Change cron test to avoid failing on Xh 59 minutes.
=> [backend] Fix cron test failed

openbas-front/src/admin/components/atomic_testings/atomic_testing/Index.tsx, openbas-front/src/admin/components/simulations/simulation/injects/InjectIndex.tsx, openbas-front/src/utils/inject/injectUtils.ts
* New payload info tab was visible for "Atomic Testing" but not for "Simulation"
=> [frontend] Fix payload info tab not visible for simulations

openbas-front/src/admin/components/assets/endpoints/EndpointsDialogAdding.tsx
* Default filters for asset selection when populating an inject should not filter by architecture if payload's architecture  is "All architectures"
N/A
=> [frontend] Don't add asset arch filter if payload is all archs

openbas-front/src/admin/components/lessons/exercises/LessonsObjectives.js, openbas-front/src/admin/components/lessons/scenarios/LessonsObjectives.js, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
* Replace deprecated ListItemSecondaryAction component by arguments secondaryAction on ListItem component
https://www.notion.so/filigran/15b8fce17f2a81e2a723e47c0cfd7c0f?v=15b8fce17f2a81df958f000ca602ba74&p=15b8fce17f2a8112aec1f245aad6ebe0&pm=s
=> [frontend] replace deprecated ListItemSecondaryAction component

openbas-api/src/test/java/io/openbas/rest/exercise/ExerciseApiStatusTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/ExerciseFixture.java
* Mock `Instant.now` and `Clock.systemDefaultZone` to get predictable times when production code calls `Instant.now()` and `LocalDateTime.now()`
I only changed the tests that depended on waiting for some time and fetch back the injects (i.e. time based tests); other tests don't seem to be affected by passing time.
=> [tests] Explicitly mock Instant.now to fix test flakiness

.github/PULL_REQUEST_TEMPLATE.md
As part of the retrospective of the milestone 1.10.0 we decided to add a line in the PR request template to explicitly request developers to implement a test that will cover the bug if their PR is a bug fix.
=> updated the PR template

openbas-front/src/admin/components/common/injects/CreateInjectDetails.js, openbas-front/src/admin/components/common/injects/InjectDefinition.js, openbas-front/src/admin/components/common/injects/InjectForm.js, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/UpdateInjectDetails.js, openbas-front/src/admin/components/lessons/SendLessonsForm.js, openbas-front/src/admin/components/settings/groups/GroupForm.js, openbas-front/src/admin/components/settings/users/UserForm.js, openbas-front/src/admin/components/simulations/simulation/controls/ComcheckForm.js, openbas-front/src/admin/components/simulations/simulation/injects/QuickInject.js, openbas-front/src/admin/components/simulations/simulation/mails/CommunicationForm.js, openbas-front/src/components/fields/FieldArray.tsx, openbas-front/src/components/fields/OldRichTextField.jsx, openbas-front/src/components/fields/OldSelectField.jsx, openbas-front/src/components/fields/OldSwitchField.js, openbas-front/src/components/fields/RichTextField.tsx, openbas-front/src/components/fields/SelectField.jsx, openbas-front/src/components/fields/SliderField.js, openbas-front/src/components/fields/SwitchField.tsx, openbas-front/src/components/fields/TextField.js, openbas-front/src/utils/KillChainPhaseUtils.ts
* Closes #2038 
* In files related to Inject Form (CreateInjectDetails.js, UpdateInjectDetails.js,  InjectDefinition.js, InjectForm.js )
* replace react-final-form by react-hook-form
* replace deprecated old fields from new one
* rename RichTextField by OldRichTextField  + create RichTextField 
* rename SwitchField by OldSwitchField  + create RichTextField 
* create FieldArray to not use FieldArray component from React-final-form
=> [frontend] remove final-form from inject form

openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/common/injects/InjectsListButtons.tsx
* [frontend] allow only selected injects to be exported
* Closes #2111 
*
=> [frontend] When I select injects and export them, the entire list is exported

openbas-front/src/admin/components/common/injects/CreateInject.tsx, openbas-front/src/admin/components/injects/InjectTestList.tsx
* In the CreateInject screen: Removed the secondary action in the header to fix the layout
*  In the CreateInject screen: Added margin between the Attack patterns
* In the TestInject screen: removed the class from the ListItem as it was added to the ListButton also which was adding 2 times the padding
Before 
After
* Closes #1842
*
=> [frontend] Layout of inject lists is not correct in create injects Issue/1842

openbas-front/src/admin/components/simulations/simulation/injects/InjectIndex.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx, openbas-front/src/components/Breadcrumbs.tsx
* Closes https://github.com/OpenBAS-Platform/openbas/issues/1936
=> Breadcrumb in inject details is not consistent

openbas-api/src/main/java/io/openbas/rest/challenge/ChallengeApi.java, openbas-api/src/main/java/io/openbas/rest/helper/RestBehavior.java
* Closes https://github.com/OpenBAS-Platform/openbas/issues/1783
=> [backend] Fix Regular expression injection

openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetResultsDetail.tsx
* Fixing the card layout used to display the inject result so the the menu is visible
Before
After
* Closes #1642 
*
=> * Fixing the card layout used to display the inject result Issue/1642

openbas-front/src/components/common/queryable/filter/FilterChipValues.tsx
* Fix or a bug when adding an empty filter in a datatable
* No issue created
To reproduce the bug before this fix, follow these steps:
- Go to any datatable where filters can be added (example: list of injects for a given scenario)
- Add a new filter (example: type)
- click outside the box, without setting any value
=> [frontend] fix: fixed adding empty filters on datatables

openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java
* Fix on 500 errors when importing a scenario
*
* Closes #2144 
*
=> [backend] Fix on 500 errors when importing a scenario (#2144)

openbas-api/src/main/java/io/openbas/rest/inject/service/ExecutableInjectService.java
=> [backend] handle multilines with cmd

openbas-api/src/main/java/io/openbas/rest/asset_group/AssetGroupApi.java, openbas-api/src/main/java/io/openbas/rest/user/UserApi.java, openbas-api/src/main/java/io/openbas/rest/user/form/user/UserOutput.java, openbas-api/src/main/java/io/openbas/rest/user/helper/UserQueryHelper.java, openbas-api/src/main/java/io/openbas/rest/user/service/UserCriteriaBuilderService.java, openbas-front/src/actions/User.js, openbas-front/src/admin/components/assets/asset_groups/AssetGroupDialogAdding.tsx, openbas-front/src/admin/components/common/injects/InjectAddTeams.tsx, openbas-front/src/admin/components/settings/groups/GroupManageUsers.tsx, openbas-front/src/admin/components/settings/groups/GroupPopover.js, openbas-front/src/admin/components/settings/users/Users.js, openbas-front/src/components/common/SelectList.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/specification/UserSpecification.java
* Add pagination to user management in group
* Add UserOutput to fit front end usage
* Closes https://github.com/OpenBAS-Platform/openbas/issues/2077
=> In Add users to group, only the first 10 can be viewed or selected

openbas-api/src/main/java/io/openbas/rest/asset_group/AssetGroupApi.java, openbas-api/src/test/java/io/openbas/rest/asset_group/AssetGroupApiTest.java, openbas-api/src/test/java/io/openbas/rest/asset_group/AssetGroupTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/AssetGroupFixture.java, openbas-framework/src/main/java/io/openbas/asset/AssetGroupService.java
=> [Backend]Test asset groups creation/update (#1494)

openbas-api/src/test/java/io/openbas/rest/PlayerApiTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/OrganizationFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/PlayerFixture.java
=> [Backend]Test player creation/update

openbas-api/src/main/java/io/openbas/rest/executor/ExecutorApi.java, openbas-api/src/main/java/io/openbas/rest/injector/InjectorApi.java, openbas-api/src/main/java/io/openbas/utils/AgentUtils.java
* Closes https://github.com/OpenBAS-Platform/openbas/issues/1782
* Closes https://github.com/OpenBAS-Platform/openbas/issues/1784
=> [backend] Fix Server-Side Request Forgery

openbas-front/src/utils/hooks/useDataLoader.js
=> [frontend] use client time for last ping date in sse client (#2126)

openbas-front/src/admin/components/assets/asset_groups/AssetGroups.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroupsList.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointsList.tsx, openbas-front/src/admin/components/common/injects/CreateInjectDetails.js, openbas-front/src/admin/components/common/injects/ResponsePie.tsx, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/UpdateInjectDetails.js
* Fix missing description and tags fields on injectForm (refact changed reference of tagField.js to TagField.tsx... and the behavior is not the same) : 
* Improve ui for targets assets : 
* Fix internal error for sort by tags on assetgroups list
* Improve ui for Humans Reponse : validation needed button -: Center button
=> [frontend] Fix missing fields in injectForm and improve ui

openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts, openbas-front/src/utils/Action.ts
* [backend] feat: changed return of bulk delete to return list of deleted injects
* [frontend] fix: fixed total number of elements not being updated when creating or deleting an inject
* [frontend] fix: fixed bulk delete not being reflected in datatables without refresh
* Fixes some bugs from issue #1961
=> [backend][frontend] Fixed an issue on injects where total number of injects was not correctly updated and bulk delete didn't refresh results

openbas-front/src/actions/Inject.js, openbas-front/src/admin/components/common/Context.ts, openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts, openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts, openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx, openbas-front/src/utils/Action.ts
* [frontend] fix: bulk delete and update now ignores store
* [frontend] fix: bulk update now correctly refreshes the data table
* [frontend] feat: bulk test and delete now display a loading animation
* Related to #1961
=> [frontend] fixes bulk operations not refreshing the datatables correctly

openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java
* fix python injector missing callback route
*
*
=> [backend] fix python injector missing callback route (#2230)

openbas-model/src/main/java/io/openbas/database/model/Agent.java
=> [backend] pass agent active threshold to 1h (#2234)

openbas-api/src/main/java/io/openbas/rest/asset/endpoint/EndpointApi.java, openbas-model/src/main/java/io/openbas/database/model/AssetAgentJob.java, openbas-model/src/main/java/io/openbas/database/specification/AssetAgentJobSpecification.java
=> [backend] bring back deprecated routes to let agents upgrade (#2247)

openbas-api/src/main/java/io/openbas/executors/ExecutorHelper.java, openbas-api/src/main/java/io/openbas/executors/crowdstrike/service/CrowdStrikeExecutorContextService.java, openbas-api/src/main/java/io/openbas/executors/openbas/service/OpenBASExecutorContextService.java, openbas-api/src/main/java/io/openbas/executors/tanium/service/TaniumExecutorContextService.java
* Closes https://github.com/OpenBAS-Platform/openbas/issues/2263
=> [backend] Added Agent ID at the implant command level for third-party executors

openbas-api/src/main/java/io/openbas/executors/caldera/service/CalderaExecutorContextService.java
* Add agentId to execute an OpenBAS payload with a Caldera agent
* Closes #2283
=> [backend] Fix Caldera agent with OpenBAS payload

.circleci/config.yml
* Release artifacts should package application.properties with expanded variables, not the placeholders
* Closes https://github.com/OpenBAS-Platform/docs/issues/91
The raw application.properties file contains placeholders to help with development (as to not disseminate the same data everywhere such as product version), but this can't be used to run a production server from a prebuilt jar.
Even though it seems unnecessary purely for running (a version of application.properties with expanded vars is embedded into the prebuilt jar), it is useful for users to have a quasi exhaustive config file to peruse possible switches and keys. It seems appropriate that the provided file would allow for running the jar with the same default values as set in the embedded version.
=> [tool] Release artifacts to package expanded application.properties (docs#91)

openbas-api/src/main/java/io/openbas/execution/ExecutableInject.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-api/src/test/java/io/openbas/rest/exercise/ExerciseApiStatusTest.java, openbas-api/src/test/java/io/openbas/rest/inject/service/InjectServiceTest.java
* updating the setInjectStatusAndExecuteInject method to set the status after calling initializeInjectStatus 
* moved the call to the initializeInjectStatus  ouf of the "if needsExecutor" so the status is created for the external excutors that are pulling the status from the db
* Closes #2220
*
=> Fix the regression on executing external injects  Issue/2220

openbas-api/src/main/java/io/openbas/rest/inject/form/InjectExecutionInput.java
*
*
* Closes #2308
*
…ith what's actually available
=> [backend] add needed execution message not blank constraint

openbas-api/src/test/java/io/openbas/rest/exercise/ExerciseApiStatusTest.java
* Add time mocks to more tests to avoid flakiness
=> [tests] less flakiness in exercise status tests

openbas-front/src/admin/components/common/injects/Injects.tsx, openbas-front/src/admin/components/common/injects/InjectsListButtons.tsx, openbas-front/src/utils/hooks/useEntityToggle.ts
* Fix bulk actions on sparse selection
* Fix #2328
=> [frontend] Fix bulk actions on sparse selection (#2328)

openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
* Filter out disabled inject from timeline
*
* Closes #2294
*
=> [frontend] Fix timeline ui

openbas-api/src/test/java/io/openbas/database/model/ExerciseTest.java, openbas-api/src/test/java/io/openbas/database/model/InjectTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/InjectFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/PauseFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/ExerciseComposer.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/PauseComposer.java
* Correctly account for pause times in inject start date computation
* Closes #2282 
Tests are better implemented with composers hence I propose this PR to release branch. Another PR with just the code fix is going to master.
There's a drive-by fix on the schema because current pause was being persisted assuming the provided instant was local time, when in reality it was provided as UTC => the backend would compute an incorrect UTC time to persist. It was low impact but needed to be addressed.
=> [backend] Account for all relevant pauses in inject start date computation (#2282)

openbas-api/src/main/resources/application.properties
* More comments to help setting up the mandatory dependencies in application.properties
* Contributes to https://github.com/OpenBAS-Platform/docs/issues/89
=> [doc] add comments to critical sections of the application.properties file (docs/#89)

openbas-api/src/main/java/io/openbas/injectors/caldera/CalderaExecutor.java, openbas-api/src/main/java/io/openbas/migration/V3_53__Update_Commands_In_Inject_Status.java, openbas-api/src/main/java/io/openbas/migration/V3_65__Update_Inject_Status_status_payload.java, openbas-api/src/main/java/io/openbas/rest/atomic_testing/form/StatusPayloadOutput.java, openbas-api/src/main/java/io/openbas/utils/InjectUtils.java, openbas-api/src/main/java/io/openbas/utils/PayloadMapper.java, openbas-api/src/test/java/io/openbas/utils/fixtures/InjectStatusFixture.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingDetail.tsx, openbas-front/src/admin/components/common/injects/InjectPopover.tsx, openbas-front/src/admin/components/injects/InjectTestDetail.tsx, openbas-front/src/admin/components/injects/InjectTestPopover.tsx, openbas-front/src/admin/components/injects/InjectTestReplayAll.tsx, openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/inject/injectUtils.ts, openbas-model/src/main/java/io/openbas/database/model/InjectStatus.java, openbas-model/src/main/java/io/openbas/database/model/StatusPayload.java
* Complete info for injects from other sources (caldera, ..): name, description, command...
* Filter page paylaod detail for injects type channel, challenge
* Clean ui InjectTests (remove ack date, total count..)
* Fix notification when an inject is tested: injectTitle was not displayed correctly
* Remove legacy code for results on injectPopover
* Closes #2311 
*
=> [backend] Build payloadOutput for Caldera injects 

openbas-front/src/admin/components/assets/endpoints/endpoint/Endpoint.tsx
=> [frontend] Correct spacing between papers in endpoint details page (#2348)

openbas-api/src/main/java/io/openbas/rest/settings/PlatformSettingsApi.java, openbas-api/src/main/java/io/openbas/rest/settings/form/PolicyInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/SettingsEnterpriseEditionUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/SettingsPlatformWhitemarkUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/SettingsUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/ThemeInput.java, openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java
* Adding swagger documentation on Settings Api endpoints
*
* 
*
=> [backend] Adding swagger documentation on Settings Api endpoints

openbas-api/src/main/java/io/openbas/rest/settings/PlatformSettingsApi.java, openbas-api/src/main/java/io/openbas/rest/settings/form/PolicyInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/SettingsEnterpriseEditionUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/SettingsPlatformWhitemarkUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/SettingsUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/ThemeInput.java, openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java, openbas-api/src/main/java/io/openbas/rest/tag/TagApi.java, openbas-api/src/main/java/io/openbas/rest/tag/form/TagBaseInput.java, openbas-api/src/main/java/io/openbas/rest/tag/form/TagCreateInput.java, openbas-api/src/main/java/io/openbas/rest/tag/form/TagUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/tag_rule/TagRuleApi.java, openbas-api/src/main/java/io/openbas/rest/tag_rule/form/TagRuleInput.java, openbas-api/src/main/java/io/openbas/rest/tag_rule/form/TagRuleOutput.java, openbas-api/src/main/java/io/openbas/rest/team/TeamApi.java, openbas-api/src/main/java/io/openbas/rest/user/UserApi.java, openbas-model/src/main/java/io/openbas/database/model/Tag.java
* Adding swagger documentation on Tags and TagRules endpoints
*
* 
*
=> [backend] Adding swagger documentation on Tags and TagRules endpoints

openbas-api/src/main/java/io/openbas/rest/helper/UserRoleDescriptionCustomizer.java, openbas-api/src/main/java/io/openbas/rest/settings/PlatformSettingsApi.java, openbas-api/src/main/java/io/openbas/rest/settings/form/PolicyInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/SettingsEnterpriseEditionUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/SettingsUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/settings/form/ThemeInput.java, openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java, openbas-api/src/main/java/io/openbas/rest/tag/TagApi.java, openbas-api/src/main/java/io/openbas/rest/tag/form/TagBaseInput.java, openbas-api/src/main/java/io/openbas/rest/tag/form/TagCreateInput.java, openbas-api/src/main/java/io/openbas/rest/tag/form/TagUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/tag_rule/TagRuleApi.java, openbas-api/src/main/java/io/openbas/rest/tag_rule/form/TagRuleInput.java, openbas-api/src/main/java/io/openbas/rest/tag_rule/form/TagRuleOutput.java, openbas-api/src/main/java/io/openbas/rest/team/TeamApi.java, openbas-api/src/main/java/io/openbas/rest/team/form/TeamBaseInput.java, openbas-api/src/main/java/io/openbas/rest/team/form/TeamCreateInput.java, openbas-api/src/main/java/io/openbas/rest/team/form/TeamUpdateInput.java, openbas-api/src/main/java/io/openbas/rest/team/form/UpdateUsersTeamInput.java, openbas-api/src/main/java/io/openbas/rest/team/output/TeamOutput.java, openbas-api/src/main/java/io/openbas/rest/user/UserApi.java, openbas-model/src/main/java/io/openbas/database/model/Tag.java, openbas-model/src/main/java/io/openbas/database/model/Team.java, openbas-model/src/main/java/io/openbas/database/model/TeamSimple.java
* Adding Swagger doc on teams endpoints
*
* 
*
=> Adding Swagger doc on teams endpoints

openbas-front/src/admin/components/components/documents/Documents.js
* When adding a document that already existed, it was added a second time to the list of documents even though it was just updated, leading to confusion.
*
* Closes #2435
*
=> Fix upload documents

openbas-front/src/admin/components/assets/asset_groups/AssetGroupManagement.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointPopover.tsx, openbas-front/src/admin/components/assets/endpoints/EndpointsList.tsx, openbas-front/src/utils/Localization.js
* Dynamic assets don't have an option to be removed from asset groups that define a filter that incliuded said asset
* Fix #2434 
* Possible to manually add asset that is already part of the asset group dynamically
=> [frontend] remove option to remove dynamic asset from asset group (#2434)

openbas-api/src/main/java/io/openbas/rest/document/DocumentService.java, openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java, openbas-api/src/main/java/io/openbas/rest/inject/form/InjectDependencyInput.java, openbas-api/src/main/java/io/openbas/rest/inject/form/InjectDocumentInput.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-api/src/main/java/io/openbas/rest/injector_contract/InjectorContractService.java, openbas-api/src/main/java/io/openbas/rest/tag/TagService.java, openbas-api/src/main/java/io/openbas/service/UserService.java, openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java, openbas-api/src/main/java/io/openbas/utils/ResultUtils.java, openbas-framework/src/main/java/io/openbas/utils/StringUtils.java, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/expectations/InjectExpectations.tsx, openbas-front/src/admin/components/common/injects/form/InjectDefinition.js, openbas-front/src/admin/components/simulations/simulation/injects/QuickInject.js, openbas-model/src/main/java/io/openbas/database/raw/RawUser.java
* https://github.com/OpenBAS-Platform/openbas/issues/2316
=> When I create a technical inject in a simulation and I remove the expectation, expectations still there

openbas-framework/src/main/java/io/openbas/utils/FilterUtilsJpa.java, openbas-framework/src/main/java/io/openbas/utils/OperationUtilsJpa.java
* [backend] fix: fixed an issue where the OR was treated as an AND in filters for "not contains" operator
* [backend] fix: fixed an issue where filter's operator "empty" and "not empty" didn't work
* Relates to #1958
=> [backend] fix: Filters issue on not contains, empty and not empty

openbas-api/src/main/java/io/openbas/config/AppConfig.java, openbas-api/src/main/java/io/openbas/config/AppPyroscopeConfig.java, openbas-api/src/main/java/io/openbas/telemetry/PyroscopeConfig.java, openbas-api/src/main/java/io/openbas/telemetry/PyroscopePropertiesConfig.java, openbas-api/src/main/resources/application.properties, openbas-dev/docker-compose.yml, pom.xml
* Adding Pyroscope
*
* Closes #2472 
*
=> Adding pyroscope to ease debugging

openbas-front/src/admin/Index.tsx, openbas-front/src/admin/components/Dashboard.tsx, openbas-front/src/admin/components/assets/asset_groups/AssetGroups.tsx, openbas-front/src/admin/components/assets/endpoints/Endpoints.tsx, openbas-front/src/admin/components/assets/endpoints/endpoint/AgentList.tsx, openbas-front/src/admin/components/assets/security_platforms/SecurityPlatforms.tsx, openbas-front/src/admin/components/atomic_testings/InjectResultList.tsx, openbas-front/src/admin/components/components/challenges/Challenges.js, openbas-front/src/admin/components/components/channels/Channels.tsx, openbas-front/src/admin/components/components/documents/Documents.js, openbas-front/src/admin/components/components/lessons/LessonsTemplates.tsx, openbas-front/src/admin/components/components/teams/Teams.tsx, openbas-front/src/admin/components/payloads/Payloads.tsx, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/scenarios/scenario/Scenario.tsx, openbas-front/src/admin/components/settings/attack_patterns/AttackPatterns.js, openbas-front/src/admin/components/settings/kill_chain_phases/KillChainPhases.js, openbas-front/src/admin/components/settings/tag_rules/TagRules.tsx, openbas-front/src/admin/components/settings/tags/Tags.js, openbas-front/src/admin/components/simulations/SimulationList.tsx, openbas-front/src/admin/components/simulations/Simulations.tsx, openbas-front/src/admin/components/teams/Organizations.tsx, openbas-front/src/admin/components/teams/Players.tsx, openbas-front/src/components/common/pagination/SortHeadersComponent.tsx, openbas-front/src/components/common/queryable/sort/SortHeadersComponentV2.tsx, openbas-front/src/components/common/queryable/style/style.ts
- Fixed a bug in the prerelease environment affecting the payload list, where the list was taking up too much width on the screen.
The ideal solution would be to migrate from flex to grid, but this requires significant effort.  
As a first step, I have opted to refactor and centralize the style code further improvements.  
Next steps:  
- Implement **SortHeadersComponentV2** and **PaginationComponentV2** consistently across all lists.  
- Mutualize code.
- Enhance the overall styling of this component.
=> Bugfix list

openbas-api/src/main/java/io/openbas/collectors/expectations_expiration_manager/service/ExpectationsExpirationManagerService.java, openbas-api/src/main/java/io/openbas/service/InjectExpectationService.java, openbas-api/src/test/java/io/openbas/rest/ExpectationApiTest.java
Currently, we have this behavior for collector results:
Score for CS result is 100 even if result is Not Prevented
Result for asset parent is Success even if result for children is Not Prevented (failed)
Ex: https://prerelease.obas.staging.filigran.io/admin/simulations/0b5e8bc0-0754-4898-9da9-7233775d9a93/injects/19b8efae-b7b5-44c7-ad44-ed6a353cfd4c
So, In this PR we **Fix** this compute result for expectation when we have different kind of collectors:
Score for every result has to be coherent with response from collectors: 
-->Prevented, detected -> ExpectedScore. 
-->Not prevented, not detected -> 0
Results for parents (assets, asset groups) have to be coherent also with response from collectors:
-->Prevented, Detected -> Success
-->Not prevented, not detected -> False
Assets
Asset …
=> [backend/frontend] Fix update result expectation from collectors

openbas-front/src/admin/components/common/injects/UpdateInject.tsx
Missing "media pressure" translation 
After fix
=> [frontend] translate injector type name in inject form

.github/workflows/release.yml, renovate.json, scripts/release.py, scripts/requirements.txt
Creation of a new release workflow with each repo being owner of their release process
=> Improve release workflow

openbas-api/src/main/java/io/openbas/App.java, openbas-api/src/main/java/io/openbas/tools/FlywayMigrationValidator.java
* Crash as soon as possible when we have two migrations with the same versions
* This helps provide a clearer error message on Drone
=> [backend] Add flyway validator to avoid same version at runtime

openbas-api/src/main/java/io/openbas/service/InjectImportService.java
* If we can't parse what is after the + or - of a relative date, we just log a warning 
* If a trigger time is empty, we ignore it when finding out if we are all relative or all absolute
* Closes #2906 
*
=> [backend] Fix on the mapper when trigger time not correctly set

openbas-api/src/main/java/io/openbas/executors/caldera/service/CalderaExecutorService.java, openbas-api/src/main/java/io/openbas/executors/crowdstrike/service/CrowdStrikeExecutorContextService.java, openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASInjector.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java, openbas-api/src/main/java/io/openbas/rest/injector/InjectorApi.java, openbas-api/src/main/java/io/openbas/service/EndpointService.java, openbas-api/src/test/java/io/openbas/executors/crowdstrike/service/CrowdstrikeExecutorServiceTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/CrowdstrikeDeviceFixture.java, openbas-front/src/admin/components/agents/Agents.tsx, openbas-front/src/utils/lang/en.json, openbas-front/src/utils/lang/fr.json, openbas-front/src/utils/lang/zh.json
* Clarify the compatible architecture for the assets
* Add the architecture in the OpenBAS implant script as Crowdstrike agent doesn't know this data
* Add error execution trace if the implant isn't compatible with the asset architecture
* Add tests
* Closes #2868
=> [backend/frontend] Manage architecture for OpenBAS implant

openbas-api/src/main/java/io/openbas/executors/tanium/service/TaniumExecutorService.java
* When registering a tanium agent, the platform is sometimes called Mac instead of MacOS
* None
=> [backend] fix: macos is sometimes called mac in tanium

openbas-front/src/admin/components/findings/FindingList.tsx, openbas-front/src/components/common/ImportUploader.tsx
* Findings: Load are not aligned with list
* Fix Import simulations & scenario is not available
=> [frontend] Fix finding padding & access import

openbas-api/src/main/java/io/openbas/migration/V3_86__Enforce_constraint_grant_scenario.java
error → "could not execute statement [ERROR: duplicate key value violates unique constraint \"grant\"\n Detail: Key (grant_group, grant_exercise, grant_name)=(d5d8c183-e6d9-4d47-b041-25e5f3bdbc62, 375280f3-7207-4f6b-95f8-2b1aaa480697, PLANNER) already exists.] [insert into grants (grant_exercise,grant_group,grant_name,grant_scenario,grant_id) values (?,?,?,?,?)]"
=> [backend] Fix simulation to scenario grants

openbas-api/src/main/java/io/openbas/export/FileExportBase.java, openbas-api/src/main/java/io/openbas/export/Mixins.java, openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/test/java/io/openbas/importer/V1_DataImporterTest.java, openbas-api/src/test/resources/importer-v1/import-scenario-with-attack-pattern.json, openbas-model/src/main/java/io/openbas/database/repository/KillChainPhaseRepository.java
* Added the KillChain phase and AttackPattern details to the export by adding another attribute containing the list of the whole objects to avoid to modify the existing attribute that only serialize the ids and is used by the front end
*In the import we now verify if the KillChainPhase / Attack Pattern exist and and we create it if it doesn't
For testing:
-> export a scenario containing payload with killchain phases
-> delete the payload and the killchain phases
-> import the scenario and verify that the payload and the killchainphase /attack pattern are created
* Closes #2016
=> [backend] add attack pattern and killchaine phase to scenario export

openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java
* Changing the job of inject execution to make use of parallelism
*
1. Create a simulation with a lot of injects launching at the same time
2. Launch it
3. It should start them all at the same time
* 
*
=> [backend] Using parallel stream to execute injects

openbas-api/pom.xml, openbas-api/src/main/java/io/openbas/config/AppSecurityConfig.java, openbas-api/src/main/java/io/openbas/config/security/OpenSamlConfig.java, openbas-api/src/main/java/io/openbas/config/security/SecurityService.java
* Remove hardcoded opensaml dependencies to fallback to Spring OpenSAML versions
* Refacto OpenSAML code to a separate class
* Closes this renovate -> https://github.com/OpenBAS-Platform/openbas/pull/2201
=> [backend] Remove hardcoded opensaml dependencies

openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/PaginatedTargetTab.tsx
* Select a default target on tab change, load
1. Add several target types to an inject (e.g. asset groups with endpoints)
2. Navigate to the inject
3. First target of first displayed tab is selected with loaded results (if applicable)
4. switch tabs
5. First target of newly navigated tab is selected, its results loaded
* Supersedes #3074
=> [frontend] Select a default target on tab change, load

openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-api/src/main/java/io/openbas/service/InjectExpectationService.java, openbas-api/src/main/java/io/openbas/service/targets/TargetService.java, openbas-api/src/main/java/io/openbas/service/targets/search/PlayerTargetSearchAdaptor.java, openbas-api/src/main/java/io/openbas/service/targets/search/TeamTargetSearchAdaptor.java, openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java, openbas-api/src/main/java/io/openbas/utils/TargetType.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectApiTest.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectTargetSearchTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/InjectFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/ExpectationComposer.java, openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/NewTargetListItem.tsx, openbas-front/src/admin/components/atomic_testings/atomic_testing/TargetListItem.tsx, openbas-front/src/components/common/queryable/filter/useRetrieveOptions.tsx, openbas-front/src/components/common/queryable/filter/useSearchOptions.tsx, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/lang/en.json, openbas-front/src/utils/lang/fr.json, openbas-front/src/utils/lang/zh.json, openbas-model/src/main/java/io/openbas/database/model/AssetGroupTarget.java, openbas-model/src/main/java/io/openbas/database/model/EndpointTarget.java, openbas-model/src/main/java/io/openbas/database/model/InjectTarget.java, openbas-model/src/main/java/io/openbas/database/model/PlayerTarget.java, openbas-model/src/main/java/io/openbas/database/model/User.java
* Add a paginated tab for Players-type inject targets
1. Create an email or sms inject and add Teams
2. Navigate to the Players tab; use filters
PS: Three options to test to create an inject with teams -> atomic testing OR exercise with inject option "all teams" OR exercise with inject without option "all teams"
* Closes #3150 
=> [frontend/backend] "players" target paginated tab

openbas-api/src/main/java/io/openbas/migration/V3_88__Enforce_constraint_asset_group_dynamic_filter.java, openbas-api/src/main/java/io/openbas/rest/asset_group/form/AssetGroupInput.java, openbas-api/src/test/java/io/openbas/rest/asset_group/AssetGroupApiTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/AssetGroupFixture.java, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/AssetGroup.java, openbas-model/src/main/java/io/openbas/database/model/Filters.java
* Add default value to dynamic filter for asset group as it's already done when you create an asset group manually
1. Add a Crowdstrike config
2. Create manual asset groups
3. Create injects with the manual asset groups and the Crowdstrike asset group
4. Check it works
* Closes #3147
=> [backend] Asset group dynamic filter not null

openbas-front/src/admin/components/assets/asset_groups/AssetGroupsList.tsx, openbas-front/src/admin/components/common/injects/CreateInject.tsx, openbas-front/src/admin/components/common/injects/UpdateInject.tsx, openbas-front/src/admin/components/common/injects/form/InjectContentFieldComponent.tsx, openbas-front/src/admin/components/common/injects/form/InjectContentForm.tsx, openbas-front/src/admin/components/common/injects/form/InjectForm.tsx, openbas-front/src/admin/components/common/injects/form/teams/InjectTeamsList.tsx
Resolved several issues related to Issue #2641:
- Fixed: Properly set the default value for the select input in the inject form.
- Fixed: Enabled the removal of the last asset, asset group, and team from the form.
- Fixed: Ensured that the inject content section opens when accessing the update inject form.
=> [frontend] fix Inject Form

openbas-api/pom.xml, pom.xml
* Enable running the OpenBAS server through the cli
```shell
$ mvn spring-boot:run -Dspring-boot.run.profiles=dev -Dspring-boot.run.main-class=io.openbas.App
```
Related: https://github.com/OpenBAS-Platform/docs/pull/156
=> [tools] configure maven to skip top POM to run through cli

openbas-api/src/main/java/io/openbas/migration/V3_90__add_automatic_finding_hash_column.java, openbas-api/src/main/java/io/openbas/rest/finding/FindingApi.java, openbas-api/src/main/java/io/openbas/service/targets/search/specifications/ExcludeMembersOfAssetGroupsSpecification.java, openbas-api/src/main/java/io/openbas/service/targets/search/specifications/IncludeDirectEndpointTargetsSpecification.java, openbas-api/src/main/java/io/openbas/service/targets/search/specifications/IncludeMembersOfAssetGroupsSpecification.java, openbas-api/src/test/java/io/openbas/rest/finding/EsFindingServiceTest.java, openbas-api/src/test/java/io/openbas/rest/finding/FindingApiTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/ExerciseFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/FindingFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/InjectComposer.java, openbas-api/src/test/resources/application.properties, openbas-model/src/main/java/io/openbas/database/model/Exercise.java, openbas-model/src/main/java/io/openbas/database/model/Inject.java, openbas-model/src/main/java/io/openbas/database/specification/FindingSpecification.java
* Only show findings from the latest FINISHED simulation of any given scenario, in Global, Scenario and Endpoint fidings views
* [drive by change] optimise some queries for target search
1. Create a scenario and equip it with an inject that will generate findings (nmap is a good candidate); preferrably an inject that will assign findings to an endpoint too
2. Run several simulations of the same scenario
3. In parallel, run a few atomic testings generating some findings, also preferrably assigning some to the same endpoint than the scenario inject.
4. Wait for simulations and atomics to end
5. Browse to global finding search: only latest finished simulation for each scenario are shown; additionally the findings from the atomic testings are also there
6. Browse to the Scenario findings: …
=> [backend] Only show findings of latest simulation for global, scenario, endpoint findings view (#3076)

openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-api/src/test/java/io/openbas/rest/inject/service/InjectServiceTest.java
* Load the default value from the injector contract when the inject is created with an empty content
*
1. Create a scenario in the UI
2. Create an inject in this scenario  using the API -> choose or create a payload that has default values in the injector contract content
3. Get the inject using the api and check that the content contains the default value
* Closes #3181 
*
=> [backend] Add default value from the injector contract whent inject's content is empty Issue/3181

openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASInjector.java
* The implant is not downloaded if the TLS 1.2 is enabled on the machine and is not added to the Powershell security protocol
1. Launch Windows payloads in a HTTP or HTTPS OpenBAS
=> [backend] Add security protocol to download the implant

openbas-api/src/main/java/io/openbas/schema/model/PropertySchemaDTO.java, openbas-api/src/test/java/io/openbas/utilstest/SchemaUtilsTest.java, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetCreationSeries.tsx, openbas-front/src/components/common/queryable/filter/FilterUtils.tsx, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/lang/en.json, openbas-front/src/utils/lang/fr.json, openbas-front/src/utils/lang/zh.json, openbas-model/src/main/java/io/openbas/annotation/Queryable.java, openbas-model/src/main/java/io/openbas/engine/model/injectexpectation/EsInjectExpectation.java, openbas-model/src/main/java/io/openbas/schema/PropertySchema.java, openbas-model/src/main/java/io/openbas/schema/SchemaUtils.java
operators
* Add filters on Expectation dimension to filter out unwanted expectations for the wrong level (e.g. asset group expectations, agent expectations)
1. Use the Horizontal bar
2. Choose Expectations
3. Use Agent, Asset, Asset group filters to include/exclude specific expectations for the unwanted/wanted types
* Contributes to #3340 
=> [backend/frontend] add filters for agent/asset/group on expectation dimension with custom operators (#3340)

openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/test/java/io/openbas/rest/scenario/ScenarioExportTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/ScenarioComposer.java
* Include payload tags in scenario export bundle
* Related #3641
* Closes #3645 
=> [backend] Include payload tags in scenario export bundle (#3641)

openbas-front/src/admin/components/simulations/simulation/injects/QuickInject.js
* Fix component setup for Quick inject
1. Set up a simulation and have it running
2. Go to Animation, "Mails" tab
3. Create a new email
4. Drawer pulls up and allows for creating a quick email inject
* Closes #3453
=> [frontend] fix quickinject component to allow quick email in running simulation (#3453)

openbas-api/src/main/java/io/openbas/injectors/caldera/CalderaExecutor.java, openbas-api/src/main/java/io/openbas/injectors/openbas/OpenBASImplantExecutor.java, openbas-api/src/main/java/io/openbas/rest/finding/FindingService.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-api/src/main/java/io/openbas/utils/ExpectationUtils.java, openbas-api/src/test/java/io/openbas/injects/Expectation/ExpectationUtilsTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/ExpectationFixture.java, openbas-model/src/main/java/io/openbas/database/model/InjectExpectationSignature.java, openbas-model/src/main/java/io/openbas/validator/Ipv4OrIpv6Validator.java
* add signatures for source and target asset 
* Chunk 1 #3359
=> [backend] add source and target expectation signatures

openbas-api/src/test/java/io/openbas/rest/DocumentApiTest.java, openbas-api/src/test/java/io/openbas/rest/PayloadApiSearchTest.java, openbas-api/src/test/java/io/openbas/rest/inject/InjectImportTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/PayloadFixture.java, openbas-front/src/admin/components/payloads/CreatePayload.js, openbas-front/src/admin/components/payloads/PayloadForm.tsx, openbas-front/src/admin/components/payloads/PayloadPopover.js, openbas-front/src/admin/components/payloads/Payloads.tsx, openbas-front/src/admin/components/payloads/form/CommandsFormTab.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/configuration/AuthorizedPerspectives.ts, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Executable.java
* Updated the Zod schema to expect a string for executable_file instead of an object with id and label, with only the id being passed now and the label handled separately.
1. Go on payload page
2. Try to create a payload of type executable file
3. Add an executable file and all the mandatory fields
4. Click on create : it supposed to work without "shloud not be empty" when you've filled in the field.
5. You can try to update it
* Closes #3425
*
=> [frontend] Impossible to create a payload of type executable file

openbas-front/src/components/common/queryable/pagination/PaginationComponentV2.tsx
* Check if the new total pages number is still superior to the actual page number
1. Go to the payload list
2. Go to the second page of the data table : "41-60"
3. filter by status=verified
4. It's supposed to come back to the first page "1-11" 
5. You can check on the other page with filter and with lot of elements
* Closes #1677
=> [frontend] Pagination is not updated when a datatable is filtered 

openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java, openbas-api/src/main/java/io/openbas/rest/exercise/service/ExerciseService.java, openbas-api/src/main/java/io/openbas/service/ScenarioService.java, openbas-api/src/test/java/io/openbas/rest/exercise/ExerciseApiTest.java, openbas-front/src/actions/exercises/exercise-action.ts, openbas-front/src/admin/components/simulations/simulation/Index.tsx, openbas-model/src/main/java/io/openbas/database/repository/ScenarioRepository.java
* Implement an api to return scenario information based on the simulation id to facilitate permission verification
1. Open a simulation page, 
2. verify that the scenario information are displayed
* #375
*
=> [backend/frontend] RBAC Implement an api to return scenario information based on the simulation id Issue/375 

openbas-api/src/test/java/io/openbas/utils/fixtures/CustomDashboardParameterFixture.java, openbas-front/src/admin/components/simulations/simulation/analysis/SimulationAnalysis.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardForm.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardHeader.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/CustomDashboardParameters.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/WidgetUtils.tsx, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/configuration/AuthorizedPerspectives.ts, openbas-front/src/admin/components/workspaces/custom_dashboards/widgets/configuration/WidgetSeriesSelection.tsx, openbas-front/src/components/common/queryable/filter/constants.ts, openbas-front/src/components/common/queryable/filter/useRetrieveOptions.tsx, openbas-front/src/components/common/queryable/filter/useSearchOptions.tsx, openbas-front/src/components/fields/AutocompleteField.tsx, openbas-front/src/components/fields/ScenarioField.tsx, openbas-front/src/components/fields/SelectFieldController.tsx, openbas-front/src/utils/Option.ts, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/lang/en.json, openbas-front/src/utils/lang/fr.json, openbas-front/src/utils/lang/zh.json, openbas-model/src/main/java/io/openbas/database/model/CustomDashboardParameters.java, openbas-model/src/main/java/io/openbas/database/model/Exercise.java, openbas-model/src/main/java/io/openbas/database/model/Scenario.java, openbas-model/src/main/java/io/openbas/database/repository/ExerciseRepository.java, openbas-model/src/main/java/io/openbas/engine/model/simulation/EsSimulation.java, openbas-model/src/main/java/io/openbas/engine/model/simulation/SimulationHandler.java
- When creating or editing a **custom dashboard**, the user can now add a **new filter parameter** called `scenario`.
- This `scenario` filter works similarly to the existing simulation filter.
- The user can:
- Choose the `scenario` filter in any widgets for the simulation dimension.
- Bind it to any `scenario` param.
- However, when the dashboard is displayed **inside a running simulation**:
- The `scenario` filter is **hidden** in the UI to prevent manual override.
- Its value is set to the scenario link to the simulation or to null.
=> [backend/frontend] Add scenario filter (#3531)

openbas-api/src/main/java/io/openbas/rest/asset/endpoint/EndpointApi.java, openbas-api/src/main/java/io/openbas/rest/asset/endpoint/form/EndpointInput.java, openbas-api/src/main/java/io/openbas/rest/asset/endpoint/form/EndpointOutput.java, openbas-api/src/main/java/io/openbas/rest/asset/form/AssetInput.java, openbas-api/src/main/java/io/openbas/service/AssetService.java, openbas-api/src/main/java/io/openbas/service/EndpointService.java, openbas-front/src/admin/components/assets/endpoints/EndpointForm.tsx, openbas-front/src/admin/components/assets/security_platforms/SecurityPlatformForm.tsx, openbas-front/src/admin/components/payloads/Payloads.tsx, openbas-front/src/utils/api-types.d.ts, openbas-model/src/main/java/io/openbas/database/model/Asset.java, openbas-model/src/main/java/io/openbas/database/model/SecurityPlatform.java, openbas-model/src/main/java/io/openbas/database/raw/impl/SimpleRawInjectExpectation.java, openbas-model/src/main/java/io/openbas/database/repository/AssetRepository.java, openbas-model/src/main/java/io/openbas/database/repository/EndpointRepository.java
* [backend] Implement API to upsert endpoints
* Closes #3856
=> [backend] Implement API to upsert endpoints (#3856)

openbas-api/src/main/java/io/openbas/injectors/challenge/ChallengeExecutor.java, openbas-api/src/main/java/io/openbas/injectors/channel/ChannelExecutor.java, openbas-api/src/main/java/io/openbas/injectors/email/EmailExecutor.java, openbas-api/src/main/java/io/openbas/injectors/email/service/EmailService.java, openbas-api/src/test/java/io/openbas/rest/scenario/ScenarioInjectTestApiTest.java, openbas-api/src/test/java/io/openbas/service/EmailServiceTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/InjectorContractFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/InjectorContractComposer.java
* Multi email contract (aka Global email) is now doing interpolation of variable.
* Caveat: when there are multiple recipients, interpolating variables of the ${user} object will not occur.
1. Create a scenario
2. Add some vars
3. Create inject of contract "multi email" (different from single email)
4. Test inject => vars interpolated
* Closes #3876 
=> [backend] enable interpolation in multi email (#3876)

openbas-api/src/main/java/io/openbas/injectors/email/EmailExecutor.java, openbas-api/src/main/java/io/openbas/rest/exercise/service/ExerciseService.java, openbas-api/src/main/java/io/openbas/rest/inject/service/InjectService.java, openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java, openbas-api/src/main/java/io/openbas/service/SecurityCoverageSendJobService.java, openbas-api/src/test/java/io/openbas/scheduler/jobs/InjectsExecutionJobTest.java, openbas-api/src/test/java/io/openbas/service/SecurityCoverageSendJobServiceTest.java, openbas-api/src/test/java/io/openbas/service/SecurityCoverageServiceTest.java, openbas-api/src/test/java/io/openbas/utils/fixtures/InjectStatusFixture.java, openbas-api/src/test/java/io/openbas/utils/fixtures/composers/InjectComposer.java
* Add trigger for creating stix coverage bundle at end of simulation
1. Import stix bundle; it creates a scenario
2. Run simulation from scenario
3. When simulation attains the "FINISHED" status, a stix coverage job is create
4. Shortly after that, a coverage is produced 
* Contributes to #3707
=> [backend] Trigger stix coverage at end of simulation (#3707)

openbas-front/src/admin/components/lessons/scenarios/Lessons.tsx, openbas-front/src/admin/components/lessons/simulations/Lessons.tsx
* Lesson learned "apply" button should only be displayed if the user has the write on the scenario/simulation, this PR is adding this check
1. Create a user with access assesment + access lesson learned
2. Go to a "Lesson learned" tab in a scenario and simulation and verify that the "apply" button is not visible
3. Add the capa "Manage assessment" to the user
4. Verify that the appy button is now visible
* #375
*
=> [frontend] RBAC: fix apply button permission

openbas-api/src/main/java/io/openbas/rest/injector_contract/InjectorContractService.java, openbas-api/src/main/java/io/openbas/rest/injector_contract/form/InjectorContractUpdateInput.java, openbas-api/src/test/java/io/openbas/rest/injector_contract/InjectorContractApiTest.java, openbas-front/src/utils/api-types.d.ts
* Allow passing external vuln IDs in the contract update input
1. Use API to update injector contract and include `contract_vulnerability_external_ids` fileds with external vuln IDs set
2. related vulns are linked to contract
* Contributes to #3334
=> [backend] allow updating contracts via API with passing external vuln IDs (#3334)

openbas-front/src/admin/components/nav/LeftBar.tsx, openbas-front/src/admin/components/settings/Index.tsx
All parameter menus should only be available to users with the access capability on Platform Settings. Without this capability, the user should not see any parameters menus, not even Taxonomies.
1. Login to user without access right on platform settings
2. You should not have parameters on the left bar
=> [frontend] Taxonomies is available with access right

openbas-front/src/components/common/pagination/SortHeadersComponent.tsx, openbas-front/src/components/common/queryable/sort/SortHeadersComponentV2.tsx, openbas-front/src/components/common/queryable/style/style.ts
* Update list styles so that only the headers are bold, while the list content remains with normal font weight.
1. Navigate to a list.
2. Verify that header titles (both sorted and unsorted) are displayed in bold.
3. Verify that list items are displayed in regular (non-bold) text.
=> [frontend] List styles - Header titles should be in bold, not the content of the lists

openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java, openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java, openbas-api/src/main/java/io/openbas/xtmhub/XtmHubConnectivityService.java, openbas-api/src/test/java/io/openbas/xtmhub/XtmHubConnectivityServiceTest.java, openbas-front/src/admin/components/scenarios/Scenarios.tsx, openbas-front/src/admin/components/settings/experience/xtm_hub/XtmHubSettings.tsx, openbas-front/src/root.tsx, openbas-front/src/utils/api-types.d.ts, openbas-front/src/utils/hooks/useAuth.ts, openbas-front/src/utils/hooks/useCheckNetwork.tsx
We don't want to display 'Register in XTM Hub' or 'import from hub' buttons in case of air-gapped environment (same behavior as for opencti). 
* In the front end, add a hook to check the connectivity with xtmhub: if there is no connectivity, hide 'import from hub' and 'Register in XTM Hub' buttons. 
* In the backend, add a connectivity check to xtmhub backend, and return this value to the frontend in the platform settings. If there is no backend connectivity, hide the button to register the platform on the hub.
- set `openbas.xtm.hub.url` to an invalid url (for example http://localhost:3008)
- activate feature flag `OPENAEV_REGISTRATION`
- on filigran experience page, check you don't see the 'Register in XTM Hub' button
- on scenario page, check you don't see the 'import from hub' button …
=> [backend/frontend] feature(xtmhub registration): add airgapped platforms check

openbas-model/src/main/java/io/openbas/service/ElasticService.java, openbas-model/src/main/java/io/openbas/service/OpenSearchService.java
* Removing filtering on user grants in the dashboard
* The current implementation doesn't take into account capa, with the RBAC we decided that any user with the dashboard permission will see the same dashboard
* The filtering will be reimplemented with the markings (issue/3768)
1. Create a dashboard with a count on injects executed 
2. Create a user with only bypass capa
3. Admin and user should see the same numbers 
* #375
*
=> [backend]RBAC remove user filter dashboard Issue/375 

openbas-api/src/main/java/io/openbas/api/xtmhub/XtmHubApi.java
* add Transaction for all XTM Hub API calls to prevent concurrency error when updating settings
Testing is only possible on prerelease because it works on other environments
1. Try to register and unregister from XTM Hub
2. Unregistration should not timeout
=> [backend] fix: add transaction for all XTM Hub API calls

openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java
* flush and clear entity manager during XTM Hub data update
1. Register and unregister XTM Hub
* Refers to #3905 
=> [backend] fix: flush and clear entity manager during settings save

openbas-front/src/admin/Index.tsx
* Protected the platform settings routes when the user does not have the right permissions
1. Give platform settings access and manage permissions to a user 
2. Login to this user 
3. Go on platform settings and update his own role to remove access and manage platform settings right
4. Refresh the page 
5. You should have the message "You don't have the right access..."
=> [frontend] Protected platform settings

openbas-api/src/main/java/io/openbas/rest/inject/service/InjectStatusService.java, openbas-api/src/test/java/io/openbas/rest/inject/service/InjectStatusServiceTest.java
* Allowing to update a status to ERROR with action COMPLETE: this will be used by the implant to mark the inject as complete and error when it crashes
* Easier to test with the implant code associated -> put a "panic" in the implant code that should trigger this api call and update the status to error
* You could try to update an implant to Complete/Error with the API 
* Closes #4096
* Implant PR: https://github.com/OpenAEV-Platform/implant/pull/79
- [NA] I added/update the relevant documentation (either on github or on notion)
=> [backend] Allowing to update a status to ERROR with action COMPLETE Issue/4096

openaev-api/src/main/java/io/openaev/opencti/connectors/impl/SecurityCoverageConnector.java, openaev-api/src/main/resources/application.properties, openaev-api/src/test/java/io/openaev/opencti/connectors/impl/SecurityCoverageConnectorTest.java, openaev-api/src/test/java/io/openaev/opencti/connectors/service/OpenCTIConnectorServiceTest.java, openaev-api/src/test/resources/application.properties
* missing null check on getUrl for when a connector is not configured
1. Unconfigured connectors should not trigger NPE in background job
* Contributes to #3705
=> [backend] null check on SecurityCoverageConnector.getUrl() (#3705)
